"""
V9 Word-to-Root Mapper — three-tier lookup.

Tier 1: Static hash (WORD_TO_ROOT dict) — O(1) direct lookup.
Tier 2: Morphological suffix stripping — tries stem in Tier 1.
Tier 3: Fallback to OBJECT_GENERIC (GAS, zero charge).

Usage:
    from engine_v9.root_map import map_to_root
    root = map_to_root("happiness")   # -> Root(name="HAPPY", ...)
"""

from __future__ import annotations
import string
from engine_v9.roots import ROOTS, Root

# ---------------------------------------------------------------------------
# Static word → root-name mapping (lowercase surface forms only)
# ---------------------------------------------------------------------------

WORD_TO_ROOT: dict[str, str] = {

    # ── Self / Other / Relation ──────────────────────────────────────────────
    "i":          "SELF",
    "me":         "SELF",
    "my":         "SELF",
    "myself":     "SELF",
    "im":         "SELF",
    "ive":        "SELF",
    "id":         "SELF",
    "ill":        "SELF",
    "mine":       "SELF",

    "you":        "OTHER",
    "your":       "OTHER",
    "yours":      "OTHER",
    "yourself":   "OTHER",
    "he":         "OTHER",
    "him":        "OTHER",
    "his":        "OTHER",
    "she":        "OTHER",
    "her":        "OTHER",
    "hers":       "OTHER",
    "they":       "OTHER",
    "them":       "OTHER",
    "their":      "OTHER",
    "we":         "OTHER",
    "us":         "OTHER",
    "our":        "OTHER",
    "it":         "OTHER",
    "its":        "OTHER",

    "someone":    "PERSON_GENERIC",
    "somebody":   "PERSON_GENERIC",
    "everyone":   "PERSON_GENERIC",
    "everybody":  "PERSON_GENERIC",
    "anyone":     "PERSON_GENERIC",
    "anybody":    "PERSON_GENERIC",
    "people":     "PERSON_GENERIC",

    "mom":        "RELATION",
    "mother":     "RELATION",
    "dad":        "RELATION",
    "father":     "RELATION",
    "brother":    "RELATION",
    "sister":     "RELATION",
    "friend":     "RELATION",
    "friends":    "RELATION",
    "family":     "RELATION",
    "husband":    "RELATION",
    "wife":       "RELATION",
    "partner":    "RELATION",
    "boyfriend":  "RELATION",
    "girlfriend": "RELATION",
    "son":        "RELATION",
    "daughter":   "RELATION",
    "child":      "RELATION",
    "children":   "RELATION",
    "kids":       "RELATION",
    "kid":        "RELATION",
    "boss":       "RELATION",
    "teacher":    "RELATION",
    "dog":        "RELATION",
    "cat":        "RELATION",
    "baby":       "RELATION",
    "ex":         "RELATION",

    # ── Positive states ──────────────────────────────────────────────────────
    "happy":      "HAPPY",
    "glad":       "HAPPY",
    "pleased":    "HAPPY",
    "joy":        "HAPPY",
    "joyful":     "HAPPY",
    "joyous":     "HAPPY",

    "excited":    "EXCITED",
    "thrilled":   "EXCITED",
    "pumped":     "EXCITED",
    "stoked":     "EXCITED",
    "ecstatic":   "EXCITED",
    "elated":     "EXCITED",
    "overjoyed":  "EXCITED",

    "grateful":   "GRATEFUL",
    "thankful":   "GRATEFUL",
    "appreciative": "GRATEFUL",

    "relieved":   "RELIEVED",

    "proud":      "PROUD",

    "content":    "CONTENT",
    "satisfied":  "CONTENT",
    "comfortable": "CONTENT",

    "amused":     "AMUSED",
    "entertained": "AMUSED",

    "hopeful":    "HOPEFUL",
    "optimistic": "HOPEFUL",

    "love":       "LOVED",
    "loved":      "LOVED",
    "adore":      "LOVED",
    "cherish":    "LOVED",

    # ── Negative states ──────────────────────────────────────────────────────
    "sad":        "SAD",
    "unhappy":    "SAD",
    "miserable":  "SAD",
    "down":       "SAD",
    "depressed":  "SAD",
    "depression": "SAD",
    "grief":      "SAD",

    "angry":      "ANGRY",
    "furious":    "ANGRY",
    "livid":      "ANGRY",
    "enraged":    "ANGRY",
    "mad":        "ANGRY",
    "pissed":     "ANGRY",
    "irate":      "ANGRY",
    "hate":       "ANGRY",
    "hatred":     "ANGRY",
    "loathe":     "ANGRY",

    "afraid":     "AFRAID",
    "scared":     "AFRAID",
    "terrified":  "AFRAID",
    "fearful":    "AFRAID",
    "dread":      "AFRAID",

    "disgusted":  "DISGUSTED",
    "repulsed":   "DISGUSTED",
    "revolted":   "DISGUSTED",

    "ashamed":    "ASHAMED",
    "humiliated": "ASHAMED",
    "embarrassed": "ASHAMED",

    "lonely":     "LONELY",
    "isolated":   "LONELY",
    "alone":      "LONELY",

    "anxious":    "ANXIOUS",
    "nervous":    "ANXIOUS",
    "worried":    "ANXIOUS",
    "anxiety":    "ANXIOUS",
    "panic":      "ANXIOUS",

    "guilty":     "GUILTY",

    "jealous":    "JEALOUS",
    "envious":    "JEALOUS",

    "frustrated": "FRUSTRATED",
    "annoyed":    "FRUSTRATED",
    "irritated":  "FRUSTRATED",

    "exhausted":  "EXHAUSTED",
    "drained":    "EXHAUSTED",
    "burned":     "EXHAUSTED",
    "tired":      "EXHAUSTED",
    "fatigued":   "EXHAUSTED",

    "devastated": "DEVASTATED",
    "shattered":  "DEVASTATED",
    "crushed":    "DEVASTATED",

    "desperate":  "DESPAIR",
    "hopeless":   "DESPAIR",
    "despair":    "DESPAIR",

    # ── Positive qualities ───────────────────────────────────────────────────
    "good":        "POS_QUALITY",
    "great":       "POS_QUALITY",
    "nice":        "POS_QUALITY",
    "wonderful":   "POS_QUALITY",
    "amazing":     "POS_QUALITY",
    "awesome":     "POS_QUALITY",
    "excellent":   "POS_QUALITY",
    "fantastic":   "POS_QUALITY",
    "incredible":  "POS_QUALITY",
    "fine":        "POS_QUALITY",
    "perfect":     "POS_QUALITY",
    "brilliant":   "POS_QUALITY",

    "beautiful":   "BEAUTIFUL",
    "gorgeous":    "BEAUTIFUL",
    "stunning":    "BEAUTIFUL",
    "pretty":      "BEAUTIFUL",
    "lovely":      "BEAUTIFUL",

    "strong":      "STRONG",
    "powerful":    "STRONG",
    "mighty":      "STRONG",

    # ── Negative qualities ───────────────────────────────────────────────────
    "bad":         "NEG_QUALITY",
    "terrible":    "NEG_QUALITY",
    "awful":       "NEG_QUALITY",
    "horrible":    "NEG_QUALITY",
    "dreadful":    "NEG_QUALITY",
    "atrocious":   "NEG_QUALITY",
    "wrong":       "NEG_QUALITY",
    "poor":        "NEG_QUALITY",

    "ugly":        "UGLY",

    "weak":        "WEAK",
    "pathetic":    "WEAK",
    "useless":     "WEAK",

    # ── Events ──────────────────────────────────────────────────────────────
    "success":     "ACHIEVEMENT",
    "succeeded":   "ACHIEVEMENT",
    "accomplished": "ACHIEVEMENT",
    "won":         "ACHIEVEMENT",
    "winning":     "ACHIEVEMENT",
    "promotion":   "ACHIEVEMENT",
    "graduated":   "ACHIEVEMENT",
    "achievement": "ACHIEVEMENT",

    "healed":      "HEALING",
    "recovered":   "HEALING",
    "cured":       "HEALING",

    "lost":        "LOSS",
    "losing":      "LOSS",
    "loss":        "LOSS",
    "missed":      "LOSS",
    "died":        "LOSS",
    "death":       "LOSS",
    "dead":        "LOSS",

    "hurt":        "HARM",
    "injured":     "HARM",
    "wounded":     "HARM",
    "pain":        "HARM",
    "abuse":       "HARM",
    "abused":      "HARM",
    "assault":     "HARM",

    "murder":      "MURDER",
    "murdered":    "MURDER",
    "killed":      "MURDER",

    "suicide":     "CRISIS",
    "suicidal":    "CRISIS",
    "rape":        "CRISIS",
    "raped":       "CRISIS",
    "torture":     "CRISIS",
    "tortured":    "CRISIS",

    "betrayed":    "BETRAYAL",
    "betrayal":    "BETRAYAL",
    "cheated":     "BETRAYAL",
    "stabbed":     "BETRAYAL",

    # ── Social evaluation ────────────────────────────────────────────────────
    "brave":       "SOC_EVAL_POS",
    "generous":    "SOC_EVAL_POS",
    "kind":        "SOC_EVAL_POS",
    "loyal":       "SOC_EVAL_POS",
    "honest":      "SOC_EVAL_POS",
    "caring":      "SOC_EVAL_POS",

    "selfish":     "SOC_EVAL_NEG",
    "cruel":       "SOC_EVAL_NEG",
    "mean":        "SOC_EVAL_NEG",
    "liar":        "SOC_EVAL_NEG",
    "traitor":     "SOC_EVAL_NEG",
    "coward":      "SOC_EVAL_NEG",

    # ── Surprise ────────────────────────────────────────────────────────────
    "surprised":   "SURPRISE",
    "shocked":     "SURPRISE",
    "unexpected":  "SURPRISE",
    "astonished":  "SURPRISE",
    "stunned":     "SURPRISE",

    # ── Actions ─────────────────────────────────────────────────────────────
    "go":       "MOTION",
    "going":    "MOTION",
    "went":     "MOTION",
    "gone":     "MOTION",
    "run":      "MOTION",
    "running":  "MOTION",
    "ran":      "MOTION",
    "walk":     "MOTION",
    "walking":  "MOTION",
    "walked":   "MOTION",
    "come":     "MOTION",
    "came":     "MOTION",
    "coming":   "MOTION",
    "move":     "MOTION",
    "moved":    "MOTION",
    "moving":   "MOTION",

    "have":     "POSSESS",
    "had":      "POSSESS",
    "has":      "POSSESS",
    "own":      "POSSESS",
    "keep":     "POSSESS",
    "kept":     "POSSESS",

    "give":     "TRANSFER",
    "gave":     "TRANSFER",
    "giving":   "TRANSFER",
    "take":     "TRANSFER",
    "took":     "TRANSFER",
    "taking":   "TRANSFER",
    "get":      "TRANSFER",
    "got":      "TRANSFER",
    "getting":  "TRANSFER",
    "send":     "TRANSFER",
    "sent":     "TRANSFER",

    "see":      "PERCEIVE",
    "saw":      "PERCEIVE",
    "seeing":   "PERCEIVE",
    "hear":     "PERCEIVE",
    "heard":    "PERCEIVE",
    "feel":     "PERCEIVE",
    "felt":     "PERCEIVE",
    "notice":   "PERCEIVE",
    "noticed":  "PERCEIVE",

    "say":      "COMMUNICATE",
    "said":     "COMMUNICATE",
    "tell":     "COMMUNICATE",
    "told":     "COMMUNICATE",
    "speak":    "COMMUNICATE",
    "spoke":    "COMMUNICATE",
    "ask":      "COMMUNICATE",
    "asked":    "COMMUNICATE",

    "think":       "THINK",
    "thought":     "THINK",
    "know":        "THINK",
    "knew":        "THINK",
    "believe":     "THINK",
    "understand":  "THINK",
    "understood":  "THINK",
    "remember":    "THINK",
    "remembered":  "THINK",

    # ── Operators ────────────────────────────────────────────────────────────
    "very":        "INTENSIFY",
    "really":      "INTENSIFY",
    "extremely":   "INTENSIFY",
    "absolutely":  "INTENSIFY",
    "totally":     "INTENSIFY",
    "completely":  "INTENSIFY",
    "incredibly":  "INTENSIFY",
    "deeply":      "INTENSIFY",
    "truly":       "INTENSIFY",
    "super":       "INTENSIFY",
    "so":          "INTENSIFY",
    "hella":       "INTENSIFY",
    "fucking":     "INTENSIFY",
    "damn":        "INTENSIFY",
    "too":         "INTENSIFY",

    "not":         "NEGATE",
    "no":          "NEGATE",
    "never":       "NEGATE",
    "nobody":      "NEGATE",
    "nothing":     "NEGATE",
    "nowhere":     "NEGATE",
    "none":        "NEGATE",
    "nor":         "NEGATE",
    "neither":     "NEGATE",
    "dont":        "NEGATE",
    "doesnt":      "NEGATE",
    "didnt":       "NEGATE",
    "cant":        "NEGATE",
    "wont":        "NEGATE",
    "isnt":        "NEGATE",
    "wasnt":       "NEGATE",
    "arent":       "NEGATE",
    "havent":      "NEGATE",
    "hasnt":       "NEGATE",
    "wouldnt":     "NEGATE",
    "couldnt":     "NEGATE",
    "shouldnt":    "NEGATE",

    "and":         "CONNECT",
    "but":         "CONNECT",
    "or":          "CONNECT",
    "if":          "CONNECT",
    "because":     "CONNECT",
    "since":       "CONNECT",
    "although":    "CONNECT",
    "though":      "CONNECT",
    "yet":         "CONNECT",
    "however":     "CONNECT",
    "while":       "CONNECT",

    "maybe":       "HEDGE_OP",
    "perhaps":     "HEDGE_OP",
    "somewhat":    "HEDGE_OP",
    "kinda":       "HEDGE_OP",
    "sorta":       "HEDGE_OP",
    "probably":    "HEDGE_OP",
    "might":       "HEDGE_OP",

    "just":        "TIME",
    "now":         "TIME",
    "then":        "TIME",
    "already":     "TIME",
    "still":       "TIME",
    "finally":     "TIME",
    "recently":    "TIME",
    "today":       "TIME",
    "yesterday":   "TIME",
    "tomorrow":    "TIME",

    # ── Formulaic ────────────────────────────────────────────────────────────
    "hello":       "GREETING",
    "hi":          "GREETING",
    "hey":         "GREETING",
    "goodbye":     "GREETING",
    "bye":         "GREETING",

    "thanks":      "THANKS",
    "thank":       "THANKS",

    "sorry":       "APOLOGY",
    "apologize":   "APOLOGY",

    "please":      "FILLER_WORD",
    "um":          "FILLER_WORD",
    "uh":          "FILLER_WORD",
    "like":        "FILLER_WORD",
    "well":        "FILLER_WORD",
    "ok":          "FILLER_WORD",
    "okay":        "FILLER_WORD",

    # ── Function words (prevent suffix-strip misclassification) ─────────────
    "is":          "FILLER_WORD",
    "was":         "FILLER_WORD",
    "are":         "FILLER_WORD",
    "were":        "FILLER_WORD",
    "been":        "FILLER_WORD",
    "being":       "FILLER_WORD",
    "am":          "FILLER_WORD",
    "do":          "FILLER_WORD",
    "does":        "FILLER_WORD",
    "did":         "FILLER_WORD",
    "will":        "FILLER_WORD",
    "would":       "FILLER_WORD",
    "could":       "FILLER_WORD",
    "should":      "FILLER_WORD",
    "can":         "FILLER_WORD",
    "may":         "FILLER_WORD",
    "shall":       "FILLER_WORD",
    "must":        "FILLER_WORD",
    "the":         "FILLER_WORD",
    "a":           "FILLER_WORD",
    "an":          "FILLER_WORD",
    "this":        "FILLER_WORD",
    "that":        "FILLER_WORD",
    "there":       "FILLER_WORD",
    "here":        "FILLER_WORD",
    "what":        "FILLER_WORD",
    "which":       "FILLER_WORD",
    "who":         "FILLER_WORD",
    "where":       "FILLER_WORD",
    "when":        "FILLER_WORD",
    "how":         "FILLER_WORD",
    "why":         "FILLER_WORD",
    "for":         "FILLER_WORD",
    "from":        "FILLER_WORD",
    "with":        "FILLER_WORD",
    "about":       "FILLER_WORD",
    "into":        "FILLER_WORD",
    "through":     "FILLER_WORD",
    "during":      "FILLER_WORD",
    "before":      "FILLER_WORD",
    "after":       "FILLER_WORD",
    "above":       "FILLER_WORD",
    "below":       "FILLER_WORD",
    "between":     "FILLER_WORD",
    "under":       "FILLER_WORD",
    "over":        "FILLER_WORD",
    "up":          "FILLER_WORD",
    "out":         "FILLER_WORD",
    "on":          "FILLER_WORD",
    "off":         "FILLER_WORD",
    "at":          "FILLER_WORD",
    "to":          "FILLER_WORD",
    "by":          "FILLER_WORD",
    "of":          "FILLER_WORD",
    "in":          "FILLER_WORD",
    "as":          "FILLER_WORD",
    "than":        "FILLER_WORD",
    "also":        "FILLER_WORD",
    "such":        "FILLER_WORD",
    "more":        "FILLER_WORD",
    "most":        "FILLER_WORD",
    "much":        "FILLER_WORD",
    "many":        "FILLER_WORD",
    "some":        "FILLER_WORD",
    "any":         "FILLER_WORD",
    "each":        "FILLER_WORD",

    # ── Ambiguous / inflated words — override V8 auto-map ──────────────────
    # These words have high |dV| in V8 but are contextually neutral in most usage.
    # Without these overrides they steal nucleus and cause false classifications.

    # Function/structural words (should never carry charge)
    "means":       "FILLER_WORD",
    "meaning":     "FILLER_WORD",
    "kind":        "FILLER_WORD",
    "whom":        "FILLER_WORD",
    "quite":       "FILLER_WORD",
    "little":      "FILLER_WORD",
    "fact":        "FILLER_WORD",
    "instead":     "FILLER_WORD",
    "behind":      "FILLER_WORD",
    "enough":      "FILLER_WORD",
    "yes":         "FILLER_WORD",
    "passed":      "FILLER_WORD",
    "direction":   "FILLER_WORD",
    "exactly":     "FILLER_WORD",
    "information": "FILLER_WORD",
    "large":       "FILLER_WORD",
    "quickly":     "FILLER_WORD",
    "count":       "FILLER_WORD",
    "present":     "FILLER_WORD",
    "ground":      "FILLER_WORD",
    "sight":       "FILLER_WORD",
    "turned":      "FILLER_WORD",
    "turning":     "FILLER_WORD",
    "turn":        "FILLER_WORD",
    "fell":        "FILLER_WORD",
    "fall":        "FILLER_WORD",
    "falling":     "FILLER_WORD",
    "rid":         "FILLER_WORD",
    "fart":        "FILLER_WORD",
    "farts":       "FILLER_WORD",
    "riding":      "FILLER_WORD",
    "ride":        "FILLER_WORD",

    # Context-dependent (GAS phase — charge too strong for default mapping)
    # These should be near-neutral; context determines their meaning.
    "down":        "FILLER_WORD",     # "sit down" vs "feeling down" — structure decides
    "home":        "FILLER_WORD",     # "go home" is neutral
    "light":       "FILLER_WORD",     # "light" as noun/adj is neutral
    "heart":       "FILLER_WORD",     # "heart attack" vs "heart of gold" — ambiguous
    "soul":        "FILLER_WORD",     # "soul" in narrative is descriptive
    "strange":     "FILLER_WORD",     # observation, not emotion
    "wish":        "FILLER_WORD",     # "I wish" is mild, not strongly negative

    # Words V8 inflated — real charge is near zero
    "solitary":    "FILLER_WORD",     # V8: dV=-90 — absurd for a descriptive word
    "separated":   "FILLER_WORD",     # V8: dV=-89 — "they separated" is often neutral
    "distracted":  "FILLER_WORD",     # V8: dV=-86 — mild annoyance at most
    "treacherous": "NEG_QUALITY",     # keep negative but not DEVASTATED
    "repulsive":   "NEG_QUALITY",     # keep negative but not ANGRY

    # Casual/slang that strips to negative stems
    "chilling":    "FILLER_WORD",     # "just chilling" = relaxing, not crisis
    "chill":       "FILLER_WORD",     # V8: dV=-70 — absurd for "chill out"
    "chills":      "FILLER_WORD",
    "hanging":     "FILLER_WORD",     # "hanging out" is neutral
    "hang":        "FILLER_WORD",
    "killing":     "HARM",            # strong negative — LIQUID phase handles "killing it" = great
    "tripping":    "FILLER_WORD",     # "tripping" = overreacting (slang)
    "trip":        "FILLER_WORD",

    # V8 auto-import overrides — words wrongly mapped by charge bucketing
    "lay":         "FILLER_WORD",     # V8: dV=+55 — "lay down" is neutral
    "became":      "FILLER_WORD",     # V8: dV=+25 — past tense of become, neutral
    "trees":       "FILLER_WORD",     # V8: dV=+25 — a tree is not emotional
    "tree":        "FILLER_WORD",
    "woke":        "FILLER_WORD",     # ambiguous slang, not emotional
    "career":      "FILLER_WORD",     # strips to "care" → POS_QUALITY (wrong)
    "remain":      "FILLER_WORD",     # V8: dV=+35 — "remained" is neutral
    "remaining":   "FILLER_WORD",
    "remained":    "FILLER_WORD",
    "remains":     "FILLER_WORD",
    "kiss":        "SLIGHT_POS",      # emotional but too strong as HAPPY nucleus
    "kissed":      "SLIGHT_POS",
    "smile":       "SLIGHT_POS",      # emotional coloring, not nucleus material
    "smiled":      "SLIGHT_POS",
    "smiling":     "SLIGHT_POS",
    "laugh":       "SLIGHT_POS",
    "laughed":     "SLIGHT_POS",
    "laughing":    "SLIGHT_POS",
    "swim":        "FILLER_WORD",     # V8: dV=+90 — swimming is not ecstatic
    "swimming":    "FILLER_WORD",
    "bacon":       "FILLER_WORD",     # V8: dV=+66 — bacon is not emotional
    "candy":       "FILLER_WORD",     # V8: dV=+62
    "cash":        "FILLER_WORD",     # V8: dV=+80
    "basic":       "FILLER_WORD",     # V8: dV=-77
    "taste":       "FILLER_WORD",     # V8: dV=+71
    "profit":      "FILLER_WORD",     # V8: dV=+66
    "lift":        "FILLER_WORD",     # V8: dV=+62
    "bid":         "FILLER_WORD",     # V8: dV=+58
    "bout":        "FILLER_WORD",     # V8: dV=+62

    # Narrative words — neutral in literary text
    "passing":     "FILLER_WORD",     # "passing by" is neutral, not SAD
    "ended":       "FILLER_WORD",     # "the chapter ended" is neutral
    "thrown":      "FILLER_WORD",     # "thrown into the mix" is neutral
    "cried":       "SLIGHT_NEG",      # emotional but often neutral in narrative

    # -less words that strip wrong or need explicit mapping
    "heartless":   "SOC_EVAL_NEG",   # "heart" overridden to FILLER, but "heartless" = cruel
    "painless":    "SLIGHT_POS",     # strips to "pain" → HARM (wrong! painless = good)
    "jobless":     "SLIGHT_NEG",     # not in V8
    "homeless":    "NEG_QUALITY",    # override V8's mapping through "home"
    "blameless":   "SLIGHT_POS",     # innocent
    "flawless":    "POS_QUALITY",    # perfect

    # Words missing from V8 entirely
    "fatal":       "NEG_QUALITY",
    "ecstasy":     "EXCITED",
    "reckless":    "NEG_QUALITY",
    "speechless":  "SURPRISE",
    "ruthless":    "SOC_EVAL_NEG",
    "relentless":  "NEG_QUALITY",
    "senseless":   "NEG_QUALITY",
    "mindless":    "NEG_QUALITY",
    "listless":    "EXHAUSTED",
    "numb":        "EXHAUSTED",
    "stuck":       "FRUSTRATED",
    "trapped":     "AFRAID",
    "empty":       "SAD",
    "pointless":   "NEG_QUALITY",
    "hollow":      "SAD",
    "drained":     "EXHAUSTED",
    "suffocating": "AFRAID",
    "drowning":    "AFRAID",
    "spiraling":   "ANXIOUS",
    "overwhelmed": "ANXIOUS",
    "overthinking":"ANXIOUS",
    "ghosting":    "SLIGHT_NEG",
    "ghosted":     "SLIGHT_NEG",

    # Ambiguous action words — neutral in most contexts
    "bumped":      "FILLER_WORD",     # "bumped up" = positive, "bumped into" = neutral
    "bump":        "FILLER_WORD",
    "beat":        "FILLER_WORD",     # "beat the boss" = positive, "beat him" = negative — ambiguous
    "beating":     "FILLER_WORD",
    "stray":       "FILLER_WORD",     # "stray dog" = neutral context
    "grade":       "FILLER_WORD",     # academic word, not emotional
    "grades":      "FILLER_WORD",
    "insanely":    "INTENSIFY",       # intensifier, not negative
    "insane":      "INTENSIFY",       # often used as positive intensifier in casual speech

    # Positive achievement/life words missing from V8
    "confident":   "POS_QUALITY",
    "confidence":  "POS_QUALITY",
    "approved":    "SLIGHT_POS",
    "approval":    "SLIGHT_POS",
    "promoted":    "ACHIEVEMENT",
    "promotion":   "ACHIEVEMENT",
    "secured":     "SLIGHT_POS",
    "funded":      "SLIGHT_POS",
    "funding":     "SLIGHT_POS",
    "agreed":      "SLIGHT_POS",
    "agreement":   "SLIGHT_POS",
    "repaired":    "SLIGHT_POS",
    "fixed":       "SLIGHT_POS",
    "cleared":     "SLIGHT_POS",
    "matched":     "SLIGHT_POS",
    "earned":      "ACHIEVEMENT",
    "graduated":   "ACHIEVEMENT",
    "accepted":    "SLIGHT_POS",
    "pregnant":    "SURPRISE",        # high-impact life event, direction depends on context
    "engaged":     "SLIGHT_POS",
    "married":     "SLIGHT_POS",
    "hired":       "ACHIEVEMENT",
    "startup":     "FILLER_WORD",
    "outfit":      "FILLER_WORD",
    "concert":     "FILLER_WORD",     # venue, not emotion — override V8's dV=+40
    "stepped":     "FILLER_WORD",

    # ── Strong evaluative words — too strong for POS/NEG_QUALITY catch-all ──
    # These are definitive judgments that need named emotional roots
    "great":       "HAPPY",
    "wonderful":   "HAPPY",
    "amazing":     "HAPPY",
    "awesome":     "HAPPY",
    "fantastic":   "HAPPY",
    "incredible":  "HAPPY",
    "brilliant":   "HAPPY",
    "magnificent": "HAPPY",
    "outstanding": "HAPPY",
    "superb":      "HAPPY",
    "excellent":   "HAPPY",
    "perfect":     "HAPPY",
    "terrible":    "SAD",
    "awful":       "SAD",
    "horrible":    "SAD",
    "dreadful":    "SAD",
    "atrocious":   "SAD",
    "disgusting":  "DISGUSTED",
    "revolting":   "DISGUSTED",
    "pathetic":    "SOC_EVAL_NEG",
    "worthless":   "SOC_EVAL_NEG",

    # ── Domain: Financial ────────────────────────────────────────────────────
    "funded":      "FIN_POS",
    "funding":     "FIN_POS",
    "approved":    "FIN_POS",
    "approval":    "FIN_POS",
    "profit":      "FIN_POS",
    "profitable":  "FIN_POS",
    "raise":       "FIN_POS",
    "bonus":       "FIN_POS",
    "savings":     "FIN_POS",
    "invested":    "FIN_POS",
    "salary":      "FILLER_WORD",
    "debt":        "FIN_NEG",
    "bankrupt":    "FIN_NEG",
    "bankruptcy":  "FIN_NEG",
    "overdue":     "FIN_NEG",
    "foreclosure": "FIN_NEG",
    "eviction":    "FIN_NEG",
    "evicted":     "FIN_NEG",
    "broke":       "FIN_NEG",         # "I'm broke" = financial
    "overdraft":   "FIN_NEG",
    "bills":       "FIN_NEG",
    "rent":        "FILLER_WORD",     # neutral unless paired with neg

    # ── Domain: Medical ──────────────────────────────────────────────────────
    "healed":      "MED_POS",
    "remission":   "MED_POS",
    "recovered":   "MED_POS",
    "recovery":    "MED_POS",
    "cured":       "MED_POS",
    "cleared":     "MED_POS",        # "scans cleared" = medical relief
    "diagnosed":   "MED_NEG",
    "diagnosis":   "MED_NEG",
    "terminal":    "MED_NEG",
    "relapsed":    "MED_NEG",
    "relapse":     "MED_NEG",
    "tumor":       "MED_NEG",
    "chemo":       "MED_NEG",
    "chemotherapy":"MED_NEG",
    "surgery":     "FILLER_WORD",    # neutral — context determines
    "hospital":    "FILLER_WORD",

    # ── Domain: Academic ─────────────────────────────────────────────────────
    "graduated":   "ACAD_POS",
    "honors":      "ACAD_POS",
    "scholarship": "ACAD_POS",
    "valedictorian":"ACAD_POS",
    "dean":        "FILLER_WORD",
    "failed":      "ACAD_NEG",
    "expelled":    "ACAD_NEG",
    "flunked":     "ACAD_NEG",
    "dropout":     "ACAD_NEG",
    "suspended":   "ACAD_NEG",

    # ── Domain: Legal ────────────────────────────────────────────────────────
    "acquitted":   "LEGAL_POS",
    "pardoned":    "LEGAL_POS",
    "innocent":    "LEGAL_POS",
    "exonerated":  "LEGAL_POS",
    "arrested":    "LEGAL_NEG",
    "convicted":   "LEGAL_NEG",
    "sentenced":   "LEGAL_NEG",
    "sued":        "LEGAL_NEG",
    "lawsuit":     "LEGAL_NEG",
    "indicted":    "LEGAL_NEG",
    "prison":      "LEGAL_NEG",
    "jail":        "LEGAL_NEG",

    # ── Domain: Career ───────────────────────────────────────────────────────
    "promoted":    "CAREER_POS",
    "promotion":   "CAREER_POS",
    "hired":       "CAREER_POS",
    "recognized":  "CAREER_POS",
    "awarded":     "CAREER_POS",
    "earned":      "CAREER_POS",
    "demoted":     "CAREER_NEG",
    "terminated":  "CAREER_NEG",
    "downsized":   "CAREER_NEG",
    "outsourced":  "CAREER_NEG",

    # ── Domain: Relationship ─────────────────────────────────────────────────
    "engaged":     "REL_POS",
    "married":     "REL_POS",
    "dating":      "REL_POS",
    "matched":     "REL_POS",
    "reconnected": "REL_POS",
    "divorced":    "REL_NEG",
    "dumped":      "REL_NEG",
    "ghosted":     "REL_NEG",
    "rejected":    "REL_NEG",
    "cheated":     "REL_NEG",
    "unfaithful":  "REL_NEG",
    "separated":   "REL_NEG",        # override FILLER_WORD — relationship context

    # Relationship verbs — need structural context to determine meaning
    "left":        "SLIGHT_NEG",      # "she left me" = abandonment, "I left the room" = neutral
    "leave":       "SLIGHT_NEG",
    "leaving":     "SLIGHT_NEG",
    "gone":        "SLIGHT_NEG",      # "she's gone" = loss context
    "lost":        "LOSS",            # override auto-map — this IS loss
    "miss":        "SLIGHT_NEG",      # "I miss her" vs "I missed the bus"
    "missing":     "SLIGHT_NEG",

    # ── Compound events (pre-joined tokens) ──────────────────────────────────
    "laidoff":      "EMPLOYMENT_LOSS",
    "firedoff":     "EMPLOYMENT_LOSS",
    "cancerfree":   "MEDICAL_RELIEF",
    "debtfree":     "MEDICAL_RELIEF",
    "painfree":     "MEDICAL_RELIEF",
    "brokeup":      "RELATIONSHIP_END",
    "passedaway":   "DEATH_EUPHEMISM",
    "brokedown":    "BREAKDOWN",
    "burnedout":    "BURNOUT",
    "pulledthrough": "RECOVERY",
    "workedout":    "RECOVERY",
    "paidoff":      "RECOVERY",
    "turnedaround": "RECOVERY",
    "pulledoff":    "ACHIEVEMENT",

    # Relationship compounds
    "leftme":       "ABANDONMENT",
    "lefthim":      "ABANDONMENT",
    "lefther":      "ABANDONMENT",
    "leftus":       "ABANDONMENT",
    "dumpedme":     "ABANDONMENT",
    "dumpedhim":    "ABANDONMENT",
    "dumpedher":    "ABANDONMENT",
    # Failure/surrender compounds
    "gaveup":       "SURRENDER",
    "givenup":      "SURRENDER",
    "letdown":      "LETDOWN",
    "messedup":     "FAILURE",
    "screwedup":    "FAILURE",
    "ranaway":      "SLIGHT_NEG",
    "movedon":      "MOVING_ON",


    # ── Auto-mapped from V8 forces_curated.py ──────────────────────────
    # Fine-bucketed: dV 15-35 → SLIGHT, dV 35-50 → QUALITY, dV>50 → named
    "abandoned": "SAD",
    "abandonment": "AFRAID",
    "abhorrent": "FRUSTRATED",
    "abominable": "FRUSTRATED",
    "abomination": "SLIGHT_NEG",
    "absurd": "SLIGHT_NEG",
    "absurdity": "SLIGHT_NEG",
    "abuser": "FRUSTRATED",
    "abusive": "SLIGHT_NEG",
    "abyss": "NEG_QUALITY",
    "acceptance": "HAPPY",
    "accident": "SLIGHT_NEG",
    "accolade": "POS_QUALITY",
    "accomplishment": "POS_QUALITY",
    "ache": "SLIGHT_NEG",
    "aches": "SLIGHT_NEG",
    "achieving": "POS_QUALITY",
    "aching": "SLIGHT_NEG",
    "acne": "SLIGHT_NEG",
    "acquittal": "HAPPY",
    "addict": "SLIGHT_NEG",
    "addicted": "SLIGHT_NEG",
    "addiction": "SLIGHT_NEG",
    "admirable": "POS_QUALITY",
    "adopt": "POS_QUALITY",
    "adoption": "EXCITED",
    "adorable": "SLIGHT_POS",
    "adultery": "DEVASTATED",
    "advance": "POS_QUALITY",
    "affair": "SLIGHT_NEG",
    "affection": "SLIGHT_POS",
    "affirming": "SLIGHT_POS",
    "aftermath": "NEG_QUALITY",
    "aggravating": "FRUSTRATED",
    "aggressive": "SLIGHT_NEG",
    "agitated": "NEG_QUALITY",
    "agonizing": "AFRAID",
    "agony": "NEG_QUALITY",
    "aimless": "SLIGHT_NEG",
    "aired": "SLIGHT_NEG",
    "alcohol": "SLIGHT_NEG",
    "alexithymia": "SLIGHT_NEG",
    "alienated": "AFRAID",
    "alimony": "SLIGHT_NEG",
    "allergy": "AFRAID",
    "alley": "NEG_QUALITY",
    "allowed": "HAPPY",
    "aloof": "SLIGHT_NEG",
    "altruistic": "POS_QUALITY",
    "alzheimers": "SLIGHT_NEG",
    "ambulance": "SLIGHT_NEG",
    "ambush": "AFRAID",
    "ambushed": "AFRAID",
    "amends": "SLIGHT_POS",
    "amputation": "NEG_QUALITY",
    "amusement": "POS_QUALITY",
    "anger": "SLIGHT_NEG",
    "anguish": "NEG_QUALITY",
    "anniversary": "SLIGHT_POS",
    "annoying": "FRUSTRATED",
    "annulment": "SLIGHT_NEG",
    "anorexia": "FRUSTRATED",
    "anorexic": "AFRAID",
    "anthem": "SLIGHT_POS",
    "anticipatory": "SLIGHT_NEG",
    "anymore": "SLIGHT_NEG",
    "apart": "AFRAID",
    "appreciates": "HAPPY",
    "appreciation": "EXCITED",
    "apprehensive": "SLIGHT_NEG",
    "aren't": "SLIGHT_NEG",
    "argument": "FRUSTRATED",
    "arguments": "SLIGHT_NEG",
    "arraigned": "NEG_QUALITY",
    "arraignment": "SLIGHT_NEG",
    "arranged": "POS_QUALITY",
    "art": "POS_QUALITY",
    "assaulted": "DEVASTATED",
    "assertive": "POS_QUALITY",
    "asshole": "SLIGHT_NEG",
    "atrocities": "NEG_QUALITY",
    "atrocity": "NEG_QUALITY",
    "attack": "NEG_QUALITY",
    "attacked": "AFRAID",
    "attacks": "NEG_QUALITY",
    "attempt": "SLIGHT_NEG",
    "attention": "HAPPY",
    "attitude": "HAPPY",
    "attractive": "HAPPY",
    "attrition": "SLIGHT_NEG",
    "audacity": "SLIGHT_NEG",
    "autoimmune": "SLIGHT_NEG",
    "autopilot": "SLIGHT_NEG",
    "avalanche": "AFRAID",
    "awe": "EXCITED",
    "awe-inspiring": "POS_QUALITY",
    "awkward": "SLIGHT_NEG",
    "backedout": "SLIGHT_NEG",
    "backoff": "SLIGHT_NEG",
    "backstabbed": "DEVASTATED",
    "backstabbing": "DEVASTATED",
    "bae": "HAPPY",
    "bail": "SLIGHT_NEG",
    "balance": "POS_QUALITY",
    "balding": "SLIGHT_NEG",
    "bamboozled": "AFRAID",
    "bang": "FRUSTRATED",
    "banger": "SLIGHT_POS",
    "bank": "POS_QUALITY",
    "bargaining": "SLIGHT_NEG",
    "barren": "SLIGHT_NEG",
    "based": "SLIGHT_POS",
    "basement": "SLIGHT_NEG",
    "bat": "NEG_QUALITY",
    "bathing": "HAPPY",
    "battered": "AFRAID",
    "bear": "POS_QUALITY",
    "beaten": "AFRAID",
    "become": "POS_QUALITY",
    "bedbound": "SAD",
    "bedridden": "SAD",
    "behave": "POS_QUALITY",
    "belittled": "SLIGHT_NEG",
    "belittling": "NEG_QUALITY",
    "beloved": "SLIGHT_POS",
    "benched": "SLIGHT_NEG",
    "benching": "SLIGHT_NEG",
    "benevolence": "POS_QUALITY",
    "benevolent": "POS_QUALITY",
    "bereaved": "AFRAID",
    "best": "SLIGHT_POS",
    "bestie": "POS_QUALITY",
    "bill": "SLIGHT_NEG",
    "binge": "NEG_QUALITY",
    "bingeing": "AFRAID",
    "binging": "SLIGHT_NEG",
    "bird": "SLIGHT_POS",
    "bite": "FRUSTRATED",
    "bitten": "DEVASTATED",
    "bitter": "NEG_QUALITY",
    "black": "SLIGHT_NEG",
    "blade": "SLIGHT_NEG",
    "blame": "SLIGHT_NEG",
    "blamed": "NEG_QUALITY",
    "bland": "SLIGHT_NEG",
    "blaring": "SLIGHT_NEG",
    "bled": "SLIGHT_NEG",
    "bleeding": "SLIGHT_NEG",
    "bless": "HAPPY",
    "blessed": "SLIGHT_POS",
    "blind": "NEG_QUALITY",
    "bloated": "SLIGHT_NEG",
    "blocked": "NEG_QUALITY",
    "bloody": "FRUSTRATED",
    "blown": "NEG_QUALITY",
    "board": "SLIGHT_POS",
    "bodyshamed": "AFRAID",
    "boiling": "NEG_QUALITY",
    "boils": "NEG_QUALITY",
    "bomb": "SLIGHT_NEG",
    "bombing": "FRUSTRATED",
    "bombs": "SLIGHT_NEG",
    "bonding": "POS_QUALITY",
    "boo": "HAPPY",
    "booed": "SLIGHT_NEG",
    "books": "HAPPY",
    "boring": "SLIGHT_NEG",
    "bother": "SLIGHT_NEG",
    "bothering": "ANGRY",
    "bounced": "SLIGHT_NEG",
    "boys": "POS_QUALITY",
    "brainrot": "SLIGHT_NEG",
    "bravery": "POS_QUALITY",
    "breadcrumbed": "NEG_QUALITY",
    "breadcrumbing": "SLIGHT_NEG",
    "break": "SLIGHT_NEG",
    "breakdown": "NEG_QUALITY",
    "breaking": "AFRAID",
    "breakthrough": "EXCITED",
    "breakup": "SLIGHT_NEG",
    "breathing": "SLIGHT_NEG",
    "breathless": "SLIGHT_NEG",
    "breathtaking": "POS_QUALITY",
    "brigaded": "NEG_QUALITY",
    "bright": "HAPPY",
    "brutal": "NEG_QUALITY",
    "bug": "SLIGHT_NEG",
    "bulimia": "AFRAID",
    "bulimic": "AFRAID",
    "bullet": "SLIGHT_NEG",
    "bullied": "AFRAID",
    "bullshit": "ANGRY",
    "bully": "FRUSTRATED",
    "bullying": "AFRAID",
    "bummed": "SLIGHT_NEG",
    "bunny": "HAPPY",
    "burden": "NEG_QUALITY",
    "buried": "NEG_QUALITY",
    "burnout": "SLIGHT_NEG",
    "business": "SLIGHT_POS",
    "bussin": "POS_QUALITY",
    "busted": "DEVASTATED",
    "busy": "SLIGHT_NEG",
    "butt": "NEG_QUALITY",
    "buying": "POS_QUALITY",
    "cacophony": "SLIGHT_NEG",
    "cage": "AFRAID",
    "calming": "POS_QUALITY",
    "calorie": "SLIGHT_NEG",
    "camebacknegative": "SLIGHT_POS",
    "can't": "SLIGHT_NEG",
    "canceled": "AFRAID",
    "cannot": "SAD",
    "cap": "SLIGHT_NEG",
    "capable": "HAPPY",
    "care": "SLIGHT_POS",
    "carefree": "HAPPY",
    "caregiver": "SLIGHT_NEG",
    "caregiving": "SLIGHT_NEG",
    "careless": "SLIGHT_NEG",
    "carnival": "POS_QUALITY",
    "casualties": "ANGRY",
    "casualty": "ANGRY",
    "catastrophe": "DEVASTATED",
    "catastrophic": "SLIGHT_NEG",
    "catastrophize": "AFRAID",
    "catfished": "FRUSTRATED",
    "caused": "NEG_QUALITY",
    "cease": "NEG_QUALITY",
    "ceased": "SLIGHT_NEG",
    "celebrate": "SLIGHT_POS",
    "celebration": "POS_QUALITY",
    "ceo": "POS_QUALITY",
    "ceremony": "HAPPY",
    "chance": "SLIGHT_POS",
    "charity": "HAPPY",
    "chase": "SLIGHT_NEG",
    "chased": "DEVASTATED",
    "cheat": "ANGRY",
    "cheating": "SLIGHT_NEG",
    "checkedout": "SLIGHT_NEG",
    "cheer": "POS_QUALITY",
    "choked": "SLIGHT_NEG",
    "choking": "NEG_QUALITY",
    "chronic": "SLIGHT_NEG",
    "citizenship": "SLIGHT_POS",
    "claim": "FRUSTRATED",
    "classic": "POS_QUALITY",
    "clearance": "EXCITED",
    "clenching": "SLIGHT_NEG",
    "clever": "SLIGHT_POS",
    "cliche": "SLIGHT_NEG",
    "climb": "EXCITED",
    "clingy": "SLIGHT_NEG",
    "cliquey": "SLIGHT_NEG",
    "closeted": "SLIGHT_NEG",
    "closing": "SLIGHT_NEG",
    "clunky": "SLIGHT_NEG",
    "clutch": "SLIGHT_POS",
    "cockroach": "DEVASTATED",
    "code": "POS_QUALITY",
    "codependency": "SLIGHT_NEG",
    "codependent": "SLIGHT_NEG",
    "coerce": "FRUSTRATED",
    "coerced": "NEG_QUALITY",
    "coercing": "NEG_QUALITY",
    "coercion": "FRUSTRATED",
    "coffin": "AFRAID",
    "colic": "SLIGHT_NEG",
    "colicky": "SLIGHT_NEG",
    "collection": "HAPPY",
    "collections": "NEG_QUALITY",
    "coma": "SAD",
    "comatose": "SAD",
    "combat": "NEG_QUALITY",
    "combative": "NEG_QUALITY",
    "combination": "POS_QUALITY",
    "comfort": "SLIGHT_POS",
    "commendation": "SLIGHT_POS",
    "committed": "POS_QUALITY",
    "compare": "SLIGHT_NEG",
    "compared": "SLIGHT_NEG",
    "comparing": "SLIGHT_NEG",
    "compassion": "SLIGHT_POS",
    "compensate": "SLIGHT_NEG",
    "compensating": "SLIGHT_NEG",
    "competes": "SLIGHT_NEG",
    "competing": "SLIGHT_NEG",
    "competition": "SLIGHT_NEG",
    "compulsion": "NEG_QUALITY",
    "compulsive": "NEG_QUALITY",
    "conceive": "SLIGHT_POS",
    "concentrate": "HAPPY",
    "concern": "FRUSTRATED",
    "concerned": "NEG_QUALITY",
    "concerning": "NEG_QUALITY",
    "concussion": "NEG_QUALITY",
    "condescending": "NEG_QUALITY",
    "condolences": "DEVASTATED",
    "confinement": "SAD",
    "conflict": "SLIGHT_NEG",
    "confront": "FRUSTRATED",
    "confused": "SLIGHT_NEG",
    "congrats": "SLIGHT_POS",
    "congratulations": "POS_QUALITY",
    "conned": "AFRAID",
    "conquer": "EXCITED",
    "conscious": "HAPPY",
    "contaminated": "NEG_QUALITY",
    "contempt": "NEG_QUALITY",
    "contemptible": "NEG_QUALITY",
    "contest": "POS_QUALITY",
    "contested": "SLIGHT_NEG",
    "contraction": "SLIGHT_NEG",
    "contractions": "SLIGHT_NEG",
    "contrived": "SLIGHT_NEG",
    "controlled": "SLIGHT_NEG",
    "controlling": "SLIGHT_NEG",
    "controls": "SLIGHT_NEG",
    "conversion": "NEG_QUALITY",
    "conviction": "DEVASTATED",
    "convinced": "HAPPY",
    "cooking": "SLIGHT_POS",
    "cope": "SLIGHT_NEG",
    "copium": "SLIGHT_NEG",
    "cornered": "SLIGHT_NEG",
    "correct": "HAPPY",
    "corrected": "SLIGHT_NEG",
    "correctly": "POS_QUALITY",
    "corrects": "SLIGHT_NEG",
    "corrupt": "ANGRY",
    "counseling": "POS_QUALITY",
    "country": "POS_QUALITY",
    "courage": "SLIGHT_POS",
    "cow": "HAPPY",
    "cracked": "SLIGHT_POS",
    "cramping": "SLIGHT_NEG",
    "cramps": "SLIGHT_NEG",
    "cranky": "ANGRY",
    "crap": "NEG_QUALITY",
    "crashing": "SLIGHT_NEG",
    "craving": "SLIGHT_NEG",
    "crazy": "SLIGHT_NEG",
    "creep": "FRUSTRATED",
    "creeping": "SLIGHT_NEG",
    "creepy": "NEG_QUALITY",
    "crescendo": "SLIGHT_POS",
    "criminal": "FRUSTRATED",
    "cringe": "SLIGHT_NEG",
    "crippling": "AFRAID",
    "crisis": "DEVASTATED",
    "critical": "AFRAID",
    "criticize": "SLIGHT_NEG",
    "criticized": "SLIGHT_NEG",
    "crowded": "POS_QUALITY",
    "cruelty": "SLIGHT_NEG",
    "cruise": "HAPPY",
    "crush": "EXCITED",
    "crushing": "AFRAID",
    "cry": "SLIGHT_NEG",
    "crybaby": "SLIGHT_NEG",
    "crying": "SLIGHT_NEG",
    "cuddle": "HAPPY",
    "culture": "HAPPY",
    "cunt": "SLIGHT_NEG",
    "cure": "POS_QUALITY",
    "current": "SLIGHT_POS",
    "curse": "AFRAID",
    "cursed": "SLIGHT_NEG",
    "custody": "SLIGHT_NEG",
    "cut": "SLIGHT_NEG",
    "cute": "SLIGHT_POS",
    "cutoff": "SLIGHT_NEG",
    "cutting": "SLIGHT_NEG",
    "cyberbullied": "AFRAID",
    "damage": "AFRAID",
    "dammit": "SLIGHT_NEG",
    "dance": "SLIGHT_POS",
    "danger": "NEG_QUALITY",
    "dare": "SLIGHT_NEG",
    "darkness": "AFRAID",
    "dazzling": "POS_QUALITY",
    "deadly": "SLIGHT_NEG",
    "deadnamed": "AFRAID",
    "deadnaming": "NEG_QUALITY",
    "deafening": "SLIGHT_NEG",
    "deaths": "NEG_QUALITY",
    "debilitating": "AFRAID",
    "debit": "NEG_QUALITY",
    "debris": "NEG_QUALITY",
    "decade": "POS_QUALITY",
    "deceived": "SLIGHT_NEG",
    "decline": "NEG_QUALITY",
    "declining": "AFRAID",
    "dedicated": "HAPPY",
    "deepfaked": "AFRAID",
    "defaulted": "AFRAID",
    "defeat": "AFRAID",
    "defective": "NEG_QUALITY",
    "defendant": "SLIGHT_NEG",
    "defensive": "SLIGHT_NEG",
    "defrauded": "AFRAID",
    "degenerative": "AFRAID",
    "degraded": "AFRAID",
    "dehumanize": "ANGRY",
    "deleted": "SLIGHT_NEG",
    "delighted": "POS_QUALITY",
    "delightful": "SLIGHT_POS",
    "delinquent": "NEG_QUALITY",
    "delulu": "SLIGHT_NEG",
    "delusional": "SLIGHT_NEG",
    "demeaned": "NEG_QUALITY",
    "demeaning": "FRUSTRATED",
    "dementia": "SLIGHT_NEG",
    "demolished": "AFRAID",
    "denial": "SLIGHT_NEG",
    "denied": "DEVASTATED",
    "dent": "NEG_QUALITY",
    "dependence": "SLIGHT_NEG",
    "dependent": "SLIGHT_NEG",
    "deplatformed": "NEG_QUALITY",
    "deplorable": "NEG_QUALITY",
    "deportation": "AFRAID",
    "deported": "AFRAID",
    "depress": "SAD",
    "depressing": "SLIGHT_NEG",
    "derivative": "SLIGHT_NEG",
    "deserve": "SLIGHT_POS",
    "desires": "EXCITED",
    "desolate": "SAD",
    "desolation": "NEG_QUALITY",
    "desperation": "AFRAID",
    "despicable": "FRUSTRATED",
    "despise": "ANGRY",
    "destroy": "SLIGHT_NEG",
    "destroyed": "AFRAID",
    "destruction": "FRUSTRATED",
    "detached": "SLIGHT_NEG",
    "detachment": "SLIGHT_NEG",
    "detained": "AFRAID",
    "detention": "AFRAID",
    "deteriorating": "AFRAID",
    "determined": "HAPPY",
    "detestable": "NEG_QUALITY",
    "detox": "NEG_QUALITY",
    "devalue": "FRUSTRATED",
    "devastating": "SLIGHT_NEG",
    "devastation": "SLIGHT_NEG",
    "devoted": "SLIGHT_POS",
    "diabetes": "SLIGHT_NEG",
    "diaspora": "SLIGHT_NEG",
    "dick": "SLIGHT_NEG",
    "didn't": "SLIGHT_NEG",
    "die": "NEG_QUALITY",
    "diet": "SLIGHT_NEG",
    "difficult": "SLIGHT_NEG",
    "dimmed": "SLIGHT_NEG",
    "directionless": "SLIGHT_NEG",
    "dirty": "SLIGHT_NEG",
    "disability": "SLIGHT_NEG",
    "disappear": "SLIGHT_NEG",
    "disappeared": "SLIGHT_NEG",
    "disappearing": "SLIGHT_NEG",
    "disappointed": "NEG_QUALITY",
    "disappointing": "NEG_QUALITY",
    "disappointment": "NEG_QUALITY",
    "disappointments": "NEG_QUALITY",
    "disaster": "SLIGHT_NEG",
    "discharge": "SLIGHT_POS",
    "disconnected": "SLIGHT_NEG",
    "disenfranchised": "AFRAID",
    "disfigured": "AFRAID",
    "disgust": "ANGRY",
    "disgusting": "FRUSTRATED",
    "dishonest": "DEVASTATED",
    "dishonorable": "AFRAID",
    "disloyal": "AFRAID",
    "disloyalty": "AFRAID",
    "dismissed": "SLIGHT_NEG",
    "dismisses": "SLIGHT_NEG",
    "dismissing": "SLIGHT_NEG",
    "dismissive": "SLIGHT_NEG",
    "disordered": "NEG_QUALITY",
    "disoriented": "NEG_QUALITY",
    "displaced": "NEG_QUALITY",
    "displacement": "NEG_QUALITY",
    "dispute": "FRUSTRATED",
    "disrespectful": "ANGRY",
    "disrupted": "SLIGHT_NEG",
    "disruption": "NEG_QUALITY",
    "dissociate": "SLIGHT_NEG",
    "dissociating": "SLIGHT_NEG",
    "dissociation": "SLIGHT_NEG",
    "dissolution": "NEG_QUALITY",
    "dissonance": "SLIGHT_NEG",
    "dissonant": "SLIGHT_NEG",
    "distant": "SAD",
    "distorted": "NEG_QUALITY",
    "distract": "AFRAID",
    "distraught": "SLIGHT_NEG",
    "disturbing": "SLIGHT_NEG",
    "ditched": "NEG_QUALITY",
    "divided": "NEG_QUALITY",
    "divorcee": "SLIGHT_NEG",
    "dizzy": "SLIGHT_NEG",
    "doesn't": "SLIGHT_NEG",
    "dogpiled": "NEG_QUALITY",
    "dominating": "SLIGHT_NEG",
    "donated": "SLIGHT_NEG",
    "doom": "NEG_QUALITY",
    "doomed": "SLIGHT_NEG",
    "doomscrolling": "SLIGHT_NEG",
    "doormat": "SLIGHT_NEG",
    "dorm": "POS_QUALITY",
    "double-crossed": "DEVASTATED",
    "doubt": "SLIGHT_NEG",
    "doubts": "SLIGHT_NEG",
    "dove": "HAPPY",
    "downsizing": "SLIGHT_NEG",
    "doxxed": "AFRAID",
    "drag": "DEVASTATED",
    "dragged": "SLIGHT_NEG",
    "dragging": "SLIGHT_NEG",
    "dragon": "EXCITED",
    "drain": "SLIGHT_NEG",
    "drains": "SLIGHT_NEG",
    "dramatic": "SLIGHT_NEG",
    "dreading": "SLIGHT_NEG",
    "dreamed": "HAPPY",
    "droppedout": "SLIGHT_NEG",
    "dropping": "DEVASTATED",
    "drought": "NEG_QUALITY",
    "drug": "AFRAID",
    "drugs": "SLIGHT_NEG",
    "drunk": "NEG_QUALITY",
    "duck": "EXCITED",
    "dull": "SLIGHT_NEG",
    "dumb": "AFRAID",
    "dump": "NEG_QUALITY",
    "dumpster": "SAD",
    "duplicitous": "AFRAID",
    "duplicity": "AFRAID",
    "dying": "SLIGHT_NEG",
    "dysmorphia": "AFRAID",
    "dysmorphic": "AFRAID",
    "dysphoria": "AFRAID",
    "dysregulated": "NEG_QUALITY",
    "dysregulation": "NEG_QUALITY",
    "eagerly": "POS_QUALITY",
    "early": "POS_QUALITY",
    "earn": "HAPPY",
    "earthquake": "AFRAID",
    "ectopic": "AFRAID",
    "efficient": "POS_QUALITY",
    "effort": "SLIGHT_POS",
    "eggshells": "SLIGHT_NEG",
    "emaciated": "DEVASTATED",
    "embarrassing": "AFRAID",
    "emerald": "HAPPY",
    "emergencies": "DEVASTATED",
    "emergency": "SLIGHT_NEG",
    "emotion": "POS_QUALITY",
    "employer": "POS_QUALITY",
    "employment": "HAPPY",
    "emptiness": "SAD",
    "enabler": "SLIGHT_NEG",
    "enabling": "SLIGHT_NEG",
    "encouraging": "SLIGHT_POS",
    "endearing": "SLIGHT_POS",
    "ending": "NEG_QUALITY",
    "endless": "SLIGHT_NEG",
    "endometriosis": "AFRAID",
    "ends": "NEG_QUALITY",
    "endurance": "SLIGHT_POS",
    "endured": "SLIGHT_POS",
    "enemy": "SLIGHT_NEG",
    "engagement": "SLIGHT_POS",
    "engineer": "POS_QUALITY",
    "engineering": "HAPPY",
    "enjoy": "SLIGHT_POS",
    "enjoyable": "SLIGHT_POS",
    "enjoyed": "HAPPY",
    "enjoying": "POS_QUALITY",
    "enmeshed": "SLIGHT_NEG",
    "enmeshment": "SLIGHT_NEG",
    "enslaved": "NEG_QUALITY",
    "entitled": "NEG_QUALITY",
    "environment": "SLIGHT_POS",
    "envy": "NEG_QUALITY",
    "epic": "POS_QUALITY",
    "equipment": "HAPPY",
    "era": "HAPPY",
    "erased": "SLIGHT_NEG",
    "escape": "SLIGHT_NEG",
    "esteem": "HAPPY",
    "estranged": "NEG_QUALITY",
    "eulogy": "SLIGHT_NEG",
    "euphoria": "EXCITED",
    "evacuated": "NEG_QUALITY",
    "evacuation": "SLIGHT_NEG",
    "event": "EXCITED",
    "everywhere": "EXCITED",
    "evicting": "AFRAID",
    "evil": "SLIGHT_NEG",
    "ex-husband": "SLIGHT_NEG",
    "ex-spouse": "SLIGHT_NEG",
    "ex-wife": "SLIGHT_NEG",
    "exact": "POS_QUALITY",
    "exaggerating": "SLIGHT_NEG",
    "excelled": "POS_QUALITY",
    "excellence": "HAPPY",
    "except": "SLIGHT_NEG",
    "exceptional": "POS_QUALITY",
    "exciting": "SLIGHT_POS",
    "excluded": "NEG_QUALITY",
    "excommunicated": "SLIGHT_NEG",
    "excruciating": "ANGRY",
    "excuse": "AFRAID",
    "exercise": "SLIGHT_POS",
    "exhaust": "SLIGHT_NEG",
    "exhausting": "SLIGHT_NEG",
    "exhilarated": "EXCITED",
    "exile": "NEG_QUALITY",
    "existential": "SLIGHT_NEG",
    "exoneration": "HAPPY",
    "expecting": "POS_QUALITY",
    "expenses": "AFRAID",
    "expired": "SLIGHT_NEG",
    "exploited": "AFRAID",
    "exploiting": "NEG_QUALITY",
    "explore": "EXCITED",
    "exposed": "NEG_QUALITY",
    "expunged": "POS_QUALITY",
    "expungement": "SLIGHT_POS",
    "extra": "AFRAID",
    "extraordinary": "POS_QUALITY",
    "extreme": "NEG_QUALITY",
    "fabulous": "HAPPY",
    "facebook": "EXCITED",
    "fail": "SLIGHT_NEG",
    "failing": "SLIGHT_NEG",
    "failure": "DEVASTATED",
    "fainted": "SLIGHT_NEG",
    "faith": "SLIGHT_POS",
    "faithless": "SLIGHT_NEG",
    "fake": "SLIGHT_NEG",
    "faked": "SLIGHT_NEG",
    "fakes": "SLIGHT_NEG",
    "faking": "SLIGHT_NEG",
    "fallen": "ANGRY",
    "falls": "SLIGHT_NEG",
    "false": "SLIGHT_NEG",
    "fam": "POS_QUALITY",
    "famine": "DEVASTATED",
    "famous": "POS_QUALITY",
    "fasting": "SLIGHT_NEG",
    "fat": "NEG_QUALITY",
    "fatigue": "SLIGHT_NEG",
    "fault": "SLIGHT_NEG",
    "fawn": "SLIGHT_NEG",
    "fear": "SLIGHT_NEG",
    "feat": "EXCITED",
    "fellow": "HAPPY",
    "felon": "AFRAID",
    "felony": "AFRAID",
    "fibromyalgia": "SLIGHT_NEG",
    "filed": "SLIGHT_NEG",
    "filth": "SAD",
    "finance": "HAPPY",
    "financial": "POS_QUALITY",
    "fired!": "NEG_QUALITY",
    "firefight": "NEG_QUALITY",
    "fireworks": "EXCITED",
    "fishing": "POS_QUALITY",
    "fit": "POS_QUALITY",
    "flabby": "SLIGHT_NEG",
    "flamed": "SLIGHT_NEG",
    "flare": "NEG_QUALITY",
    "flareup": "NEG_QUALITY",
    "flaring": "NEG_QUALITY",
    "flashback": "AFRAID",
    "flashbacks": "NEG_QUALITY",
    "flat": "SLIGHT_NEG",
    "flawed": "SLIGHT_NEG",
    "flee": "SLIGHT_NEG",
    "flex": "SLIGHT_POS",
    "flies": "NEG_QUALITY",
    "flinch": "SLIGHT_NEG",
    "flinched": "SLIGHT_NEG",
    "flinching": "SLIGHT_NEG",
    "flip": "SAD",
    "floating": "POS_QUALITY",
    "flood": "AFRAID",
    "flooded": "AFRAID",
    "flooding": "NEG_QUALITY",
    "flu": "SAD",
    "flushed": "SLIGHT_NEG",
    "fly": "SLIGHT_POS",
    "fml": "SLIGHT_NEG",
    "fomo": "SLIGHT_NEG",
    "fondly": "SLIGHT_POS",
    "foodpoisoning": "NEG_QUALITY",
    "fool": "FRUSTRATED",
    "foolish": "SLIGHT_NEG",
    "forced": "NEG_QUALITY",
    "foreclosed": "AFRAID",
    "forgettable": "SLIGHT_NEG",
    "forgetting": "SLIGHT_NEG",
    "forgive": "HAPPY",
    "forgiven": "POS_QUALITY",
    "forlorn": "SAD",
    "formulaic": "SLIGHT_NEG",
    "forsaken": "FRUSTRATED",
    "fortitude": "SLIGHT_POS",
    "fortunate": "POS_QUALITY",
    "fortunately": "HAPPY",
    "fortune": "POS_QUALITY",
    "fought": "SLIGHT_NEG",
    "founded": "SLIGHT_POS",
    "fragile": "NEG_QUALITY",
    "frail": "NEG_QUALITY",
    "fraud": "AFRAID",
    "fraudulent": "AFRAID",
    "freak": "SLIGHT_NEG",
    "freaked": "SLIGHT_NEG",
    "freakedout": "SLIGHT_NEG",
    "freaky": "ANGRY",
    "freedom": "SLIGHT_POS",
    "freeze": "SLIGHT_NEG",
    "freezing": "SLIGHT_NEG",
    "fretful": "SLIGHT_NEG",
    "fried": "SLIGHT_NEG",
    "friendless": "SAD",
    "friendship": "POS_QUALITY",
    "frightened": "SLIGHT_NEG",
    "frightening": "SLIGHT_NEG",
    "frigid": "SLIGHT_NEG",
    "froze": "SLIGHT_NEG",
    "frozen": "SLIGHT_NEG",
    "frustration": "AFRAID",
    "fuck": "FRUSTRATED",
    "fuckoff": "FRUSTRATED",
    "fugitive": "NEG_QUALITY",
    "fully": "HAPPY",
    "fumbled": "SLIGHT_NEG",
    "fuming": "FRUSTRATED",
    "funeral": "SLIGHT_NEG",
    "furlough": "SLIGHT_NEG",
    "furloughed": "NEG_QUALITY",
    "furniture": "POS_QUALITY",
    "fussy": "SLIGHT_NEG",
    "futile": "NEG_QUALITY",
    "futility": "NEG_QUALITY",
    "gambling": "SLIGHT_NEG",
    "games": "SLIGHT_POS",
    "ganged": "NEG_QUALITY",
    "garnished": "SLIGHT_NEG",
    "garnishment": "AFRAID",
    "gaslighted": "DEVASTATED",
    "gaslighting": "NEG_QUALITY",
    "gaslit": "NEG_QUALITY",
    "generic": "SLIGHT_NEG",
    "genocide": "NEG_QUALITY",
    "getout": "NEG_QUALITY",
    "ghetto": "NEG_QUALITY",
    "ghost": "SLIGHT_NEG",
    "giant": "SLIGHT_POS",
    "gifted": "POS_QUALITY",
    "girls": "POS_QUALITY",
    "glazing": "SLIGHT_NEG",
    "glorious": "POS_QUALITY",
    "glory": "POS_QUALITY",
    "goal": "SLIGHT_POS",
    "goals": "POS_QUALITY",
    "goat": "SLIGHT_POS",
    "goated": "POS_QUALITY",
    "goddamn": "SLIGHT_NEG",
    "godless": "SLIGHT_NEG",
    "goeshard": "POS_QUALITY",
    "goodness": "POS_QUALITY",
    "gosh": "SLIGHT_NEG",
    "gossip": "SLIGHT_NEG",
    "gossiping": "SLIGHT_NEG",
    "grabbed": "NEG_QUALITY",
    "graciousness": "POS_QUALITY",
    "graduate": "SLIGHT_POS",
    "grand": "POS_QUALITY",
    "granted": "SLIGHT_NEG",
    "gratitude": "HAPPY",
    "greatest": "POS_QUALITY",
    "greed": "SLIGHT_NEG",
    "greedy": "FRUSTRATED",
    "grieve": "SLIGHT_NEG",
    "grim": "NEG_QUALITY",
    "grit": "SLIGHT_POS",
    "groaning": "SLIGHT_NEG",
    "grooming": "NEG_QUALITY",
    "gross": "FRUSTRATED",
    "grotesque": "NEG_QUALITY",
    "grumpy": "ANGRY",
    "gtfo": "SLIGHT_NEG",
    "guarantee": "POS_QUALITY",
    "guard": "SLIGHT_POS",
    "guess": "SLIGHT_NEG",
    "guilt": "SLIGHT_NEG",
    "guilts": "SLIGHT_NEG",
    "gutless": "NEG_QUALITY",
    "gutted": "AFRAID",
    "gym": "SLIGHT_POS",
    "hacked": "NEG_QUALITY",
    "haha": "HAPPY",
    "hahaha": "SLIGHT_POS",
    "halcyon": "SLIGHT_POS",
    "halloween": "SLIGHT_POS",
    "handcuffed": "AFRAID",
    "handy": "HAPPY",
    "happier": "SLIGHT_POS",
    "happiest": "POS_QUALITY",
    "happily": "HAPPY",
    "happiness": "POS_QUALITY",
    "harassed": "FRUSTRATED",
    "harassing": "NEG_QUALITY",
    "harder": "SLIGHT_NEG",
    "hardest": "FRUSTRATED",
    "harm": "NEG_QUALITY",
    "harmed": "NEG_QUALITY",
    "harmful": "SLIGHT_NEG",
    "harsh": "SLIGHT_NEG",
    "hated": "FRUSTRATED",
    "haunted": "AFRAID",
    "haunting": "SLIGHT_NEG",
    "haven't": "SLIGHT_NEG",
    "hazardous": "NEG_QUALITY",
    "headache": "NEG_QUALITY",
    "heal": "POS_QUALITY",
    "healing": "SLIGHT_POS",
    "healthy": "HAPPY",
    "heartbeat": "POS_QUALITY",
    "heartbreaking": "SLIGHT_NEG",
    "heartbroken": "NEG_QUALITY",
    "heartfelt": "SLIGHT_POS",
    "heartwarming": "HAPPY",
    "heaven": "SLIGHT_POS",
    "heck": "FRUSTRATED",
    "hell": "SLIGHT_NEG",
    "help": "SLIGHT_POS",
    "helped": "SLIGHT_POS",
    "helpful": "SLIGHT_POS",
    "helping": "SLIGHT_POS",
    "helpless": "SAD",
    "hemorrhage": "AFRAID",
    "hemorrhaging": "AFRAID",
    "hermit": "SLIGHT_NEG",
    "hero": "POS_QUALITY",
    "heroic": "POS_QUALITY",
    "heroism": "EXCITED",
    "herpes": "SLIGHT_NEG",
    "hesitant": "NEG_QUALITY",
    "hid": "SLIGHT_NEG",
    "hide": "SLIGHT_NEG",
    "hiding": "SAD",
    "hilarious": "POS_QUALITY",
    "hip": "POS_QUALITY",
    "history": "SLIGHT_POS",
    "hitdifferent": "SLIGHT_POS",
    "hitting": "NEG_QUALITY",
    "holiday": "SLIGHT_POS",
    "holy": "SLIGHT_POS",
    "homebound": "NEG_QUALITY",
    "homecoming": "EXCITED",
    "homeland": "SLIGHT_POS",
    "homelessness": "AFRAID",
    "homesick": "NEG_QUALITY",
    "homesickness": "NEG_QUALITY",
    "homicide": "SLIGHT_NEG",
    "homie": "POS_QUALITY",
    "homophobia": "FRUSTRATED",
    "homophobic": "FRUSTRATED",
    "honesty": "HAPPY",
    "honor": "SLIGHT_POS",
    "honorable": "POS_QUALITY",
    "honored": "POS_QUALITY",
    "hoodwinked": "AFRAID",
    "hoovering": "NEG_QUALITY",
    "hope": "POS_QUALITY",
    "horrific": "SLIGHT_NEG",
    "horrified": "SLIGHT_NEG",
    "horrifying": "SLIGHT_NEG",
    "horse": "SLIGHT_POS",
    "hose": "EXCITED",
    "hospice": "ANGRY",
    "hostile": "FRUSTRATED",
    "housebound": "NEG_QUALITY",
    "huge": "SLIGHT_POS",
    "hugs": "HAPPY",
    "huh": "NEG_QUALITY",
    "humanity": "HAPPY",
    "humiliating": "SLIGHT_NEG",
    "hungry": "SLIGHT_NEG",
    "hunt": "NEG_QUALITY",
    "hurricane": "DEVASTATED",
    "hurricanes": "FRUSTRATED",
    "hurting": "SLIGHT_NEG",
    "hurts": "SLIGHT_NEG",
    "hype": "SLIGHT_POS",
    "hyped": "SLIGHT_POS",
    "hyperfocus": "SLIGHT_POS",
    "hyperfocusing": "SLIGHT_POS",
    "hyperventilating": "NEG_QUALITY",
    "hypervigilance": "SLIGHT_NEG",
    "hypervigilant": "NEG_QUALITY",
    "ick": "NEG_QUALITY",
    "idc": "SLIGHT_NEG",
    "ideal": "HAPPY",
    "idiot": "AFRAID",
    "ignore": "NEG_QUALITY",
    "ignored": "NEG_QUALITY",
    "ignoring": "SLIGHT_NEG",
    "immobile": "NEG_QUALITY",
    "impeccable": "POS_QUALITY",
    "impersonated": "NEG_QUALITY",
    "impersonator": "NEG_QUALITY",
    "implanted": "SLIGHT_POS",
    "impossible": "AFRAID",
    "imposter": "SLIGHT_NEG",
    "impostor": "NEG_QUALITY",
    "imprisoned": "AFRAID",
    "imprisonment": "AFRAID",
    "impulsive": "SLIGHT_NEG",
    "impulsivity": "SLIGHT_NEG",
    "inaccessible": "NEG_QUALITY",
    "inadequate": "SLIGHT_NEG",
    "inattentive": "SLIGHT_NEG",
    "incapable": "NEG_QUALITY",
    "incarcerated": "DEVASTATED",
    "incarceration": "AFRAID",
    "income": "HAPPY",
    "incompetent": "SLIGHT_NEG",
    "inconsiderate": "SAD",
    "inconsolable": "AFRAID",
    "inconvenient": "AFRAID",
    "indebted": "NEG_QUALITY",
    "independent": "POS_QUALITY",
    "indictment": "AFRAID",
    "indomitable": "SLIGHT_POS",
    "industry": "SLIGHT_POS",
    "infected": "NEG_QUALITY",
    "infection": "AFRAID",
    "inferior": "NEG_QUALITY",
    "infertile": "AFRAID",
    "infertility": "AFRAID",
    "infidelity": "DEVASTATED",
    "inflamed": "SLIGHT_NEG",
    "inflammation": "SLIGHT_NEG",
    "info": "HAPPY",
    "inform": "HAPPY",
    "informant": "SLIGHT_NEG",
    "infuriating": "SLIGHT_NEG",
    "injuries": "SLIGHT_NEG",
    "injury": "AFRAID",
    "innovated": "POS_QUALITY",
    "insecure": "NEG_QUALITY",
    "insecurities": "SLIGHT_NEG",
    "insecurity": "SLIGHT_NEG",
    "inspired": "SLIGHT_POS",
    "insufferable": "NEG_QUALITY",
    "insufficient": "SLIGHT_NEG",
    "insult": "SLIGHT_NEG",
    "insults": "SLIGHT_NEG",
    "insurance": "POS_QUALITY",
    "insurgent": "SLIGHT_NEG",
    "intelligent": "HAPPY",
    "interested": "HAPPY",
    "interrupt": "SLIGHT_NEG",
    "interrupts": "SLIGHT_NEG",
    "intimidate": "FRUSTRATED",
    "intimidated": "NEG_QUALITY",
    "intimidating": "FRUSTRATED",
    "intolerable": "AFRAID",
    "intruder": "SLIGHT_NEG",
    "intrusive": "NEG_QUALITY",
    "inundated": "NEG_QUALITY",
    "invalidate": "NEG_QUALITY",
    "invalidated": "AFRAID",
    "invalidating": "AFRAID",
    "investment": "POS_QUALITY",
    "invisible": "NEG_QUALITY",
    "involuntary": "SLIGHT_NEG",
    "irreconcilable": "NEG_QUALITY",
    "irredeemable": "SAD",
    "irrelevant": "SLIGHT_NEG",
    "irreversible": "SLIGHT_NEG",
    "isn't": "SLIGHT_NEG",
    "isolate": "NEG_QUALITY",
    "isolating": "NEG_QUALITY",
    "issues": "SLIGHT_NEG",
    "jackpot": "EXCITED",
    "jammed": "FRUSTRATED",
    "jar": "HAPPY",
    "jarring": "SLIGHT_NEG",
    "jealousy": "AFRAID",
    "jerk": "NEG_QUALITY",
    "jerks": "AFRAID",
    "join": "HAPPY",
    "joining": "HAPPY",
    "jubilant": "EXCITED",
    "judas": "DEVASTATED",
    "judge": "SLIGHT_NEG",
    "judged": "SLIGHT_NEG",
    "judges": "SLIGHT_NEG",
    "judging": "SLIGHT_NEG",
    "junk": "SLIGHT_NEG",
    "justice": "POS_QUALITY",
    "keening": "AFRAID",
    "kick": "SLIGHT_NEG",
    "kicked": "SLIGHT_NEG",
    "kickedout": "NEG_QUALITY",
    "kicking": "SLIGHT_NEG",
    "kill": "NEG_QUALITY",
    "killedit": "SLIGHT_POS",
    "killer": "SLIGHT_NEG",
    "kills": "NEG_QUALITY",
    "kindness": "SLIGHT_POS",
    "kinship": "SLIGHT_POS",
    "kitten": "SLIGHT_POS",
    "knife": "NEG_QUALITY",
    "knock": "NEG_QUALITY",
    "knot": "SLIGHT_NEG",
    "l": "SLIGHT_NEG",
    "labor": "SLIGHT_NEG",
    "lack": "NEG_QUALITY",
    "lacking": "SLIGHT_NEG",
    "lackluster": "SLIGHT_NEG",
    "lacks": "SLIGHT_NEG",
    "laid": "SLIGHT_NEG",
    "landslide": "AFRAID",
    "larger": "HAPPY",
    "lasagna": "HAPPY",
    "launched": "SLIGHT_POS",
    "law": "SLIGHT_POS",
    "laxative": "NEG_QUALITY",
    "layoff": "NEG_QUALITY",
    "layoffs": "SLIGHT_NEG",
    "lazy": "SLIGHT_NEG",
    "leaked": "NEG_QUALITY",
    "leap": "HAPPY",
    "leash": "NEG_QUALITY",
    "leaves": "SLIGHT_NEG",
    "leftovers": "SAD",
    "legendary": "HAPPY",
    "legit": "HAPPY",
    "let's": "SLIGHT_POS",
    "leveled": "AFRAID",
    "lie": "SLIGHT_NEG",
    "lied": "SLIGHT_NEG",
    "lies": "NEG_QUALITY",
    "lifeless": "NEG_QUALITY",
    "lifestyle": "HAPPY",
    "lifted": "POS_QUALITY",
    "lightheaded": "SLIGHT_NEG",
    "liked": "HAPPY",
    "limited": "SAD",
    "liquidated": "NEG_QUALITY",
    "lit": "SLIGHT_POS",
    "litter": "SAD",
    "lmfao": "SLIGHT_NEG",
    "loathing": "SLIGHT_NEG",
    "loathsome": "SLIGHT_NEG",
    "local": "SLIGHT_POS",
    "locked": "SLIGHT_NEG",
    "lockedout": "SLIGHT_NEG",
    "loneliness": "SAD",
    "loner": "SLIGHT_NEG",
    "lonesome": "SAD",
    "longing": "NEG_QUALITY",
    "loose": "HAPPY",
    "lose": "FRUSTRATED",
    "loser": "SLIGHT_NEG",
    "lottery": "EXCITED",
    "loud": "SLIGHT_NEG",
    "lovebombed": "SLIGHT_NEG",
    "lovebombing": "SLIGHT_NEG",
    "loving": "POS_QUALITY",
    "lower": "NEG_QUALITY",
    "loyalty": "HAPPY",
    "luck": "SLIGHT_POS",
    "luckily": "HAPPY",
    "lump": "SLIGHT_NEG",
    "lupus": "SLIGHT_NEG",
    "madden": "NEG_QUALITY",
    "madeit": "SLIGHT_POS",
    "madeitthrough": "SLIGHT_POS",
    "magic": "HAPPY",
    "magical": "POS_QUALITY",
    "magnanimous": "POS_QUALITY",
    "magnificent": "POS_QUALITY",
    "mail": "EXCITED",
    "majestic": "POS_QUALITY",
    "major": "SLIGHT_POS",
    "malnourished": "AFRAID",
    "mandatory": "FRUSTRATED",
    "manifesting": "SLIGHT_POS",
    "manipulate": "FRUSTRATED",
    "manipulated": "NEG_QUALITY",
    "manipulating": "NEG_QUALITY",
    "manslaughter": "ANGRY",
    "marathon": "SLIGHT_POS",
    "marginalized": "AFRAID",
    "market": "EXCITED",
    "marriage": "HAPPY",
    "marvel": "POS_QUALITY",
    "marvelous": "SLIGHT_POS",
    "masking": "SLIGHT_NEG",
    "mass": "SLIGHT_NEG",
    "massacre": "NEG_QUALITY",
    "mastered": "POS_QUALITY",
    "masterful": "POS_QUALITY",
    "masterpiece": "HAPPY",
    "mastery": "HAPPY",
    "maternal": "SLIGHT_POS",
    "math": "SLIGHT_POS",
    "meaningless": "NEG_QUALITY",
    "medal": "POS_QUALITY",
    "medevac": "NEG_QUALITY",
    "medication": "SLIGHT_NEG",
    "mediocre": "SLIGHT_NEG",
    "melancholic": "SLIGHT_NEG",
    "melancholy": "SLIGHT_NEG",
    "meltdown": "AFRAID",
    "memorial": "SLIGHT_NEG",
    "mess": "SLIGHT_NEG",
    "mid": "SLIGHT_NEG",
    "middle": "SLIGHT_POS",
    "migraine": "NEG_QUALITY",
    "millionaire": "POS_QUALITY",
    "minimizes": "SLIGHT_NEG",
    "miracle": "POS_QUALITY",
    "miscarriage": "AFRAID",
    "miscarried": "DEVASTATED",
    "misdemeanor": "SLIGHT_NEG",
    "misgendered": "NEG_QUALITY",
    "misgendering": "NEG_QUALITY",
    "mission": "HAPPY",
    "mistake": "SLIGHT_NEG",
    "mistakes": "SLIGHT_NEG",
    "mix": "POS_QUALITY",
    "moaning": "NEG_QUALITY",
    "mobbing": "AFRAID",
    "mocked": "NEG_QUALITY",
    "mocking": "NEG_QUALITY",
    "mold": "NEG_QUALITY",
    "molested": "NEG_QUALITY",
    "molesting": "NEG_QUALITY",
    "monitors": "SLIGHT_NEG",
    "monotonous": "SLIGHT_NEG",
    "monster": "AFRAID",
    "mortgage": "AFRAID",
    "mortified": "SLIGHT_NEG",
    "mosquito": "SAD",
    "motivated": "SLIGHT_POS",
    "motorcycle": "POS_QUALITY",
    "mountains": "HAPPY",
    "mourn": "AFRAID",
    "mourning": "SLIGHT_NEG",
    "muddled": "SLIGHT_NEG",
    "mundane": "SLIGHT_NEG",
    "murdering": "SLIGHT_NEG",
    "muted": "SLIGHT_NEG",
    "mutual": "HAPPY",
    "naked": "NEG_QUALITY",
    "nap": "SLIGHT_POS",
    "narc": "SLIGHT_NEG",
    "narcissist": "NEG_QUALITY",
    "narcissistic": "NEG_QUALITY",
    "national": "POS_QUALITY",
    "nausea": "SLIGHT_NEG",
    "nauseated": "FRUSTRATED",
    "nauseating": "NEG_QUALITY",
    "nauseous": "SLIGHT_NEG",
    "needles": "AFRAID",
    "needless": "NEG_QUALITY",
    "needy": "SLIGHT_NEG",
    "neglected": "SAD",
    "nerve": "EXCITED",
    "nerves": "NEG_QUALITY",
    "nevermind": "SLIGHT_NEG",
    "news": "SLIGHT_POS",
    "nicest": "HAPPY",
    "nicu": "AFRAID",
    "nightmare": "NEG_QUALITY",
    "nightmares": "AFRAID",
    "nihilism": "NEG_QUALITY",
    "nihilistic": "NEG_QUALITY",
    "noble": "HAPPY",
    "noise": "SLIGHT_NEG",
    "nonsense": "SLIGHT_NEG",
    "nonviable": "DEVASTATED",
    "noose": "NEG_QUALITY",
    "nothingness": "NEG_QUALITY",
    "numbness": "SLIGHT_NEG",
    "nvm": "SLIGHT_NEG",
    "obese": "NEG_QUALITY",
    "obligated": "SLIGHT_NEG",
    "obligation": "SLIGHT_NEG",
    "obliterated": "DEVASTATED",
    "obsession": "SLIGHT_NEG",
    "obsessive": "NEG_QUALITY",
    "obvious": "SLIGHT_NEG",
    "odd": "SAD",
    "odious": "NEG_QUALITY",
    "offboarded": "SLIGHT_NEG",
    "offboarding": "SLIGHT_NEG",
    "ohhh": "SAD",
    "oldest": "SLIGHT_NEG",
    "omg": "SLIGHT_POS",
    "oof": "SLIGHT_NEG",
    "ooo": "NEG_QUALITY",
    "opening": "EXCITED",
    "opportunities": "HAPPY",
    "opportunity": "EXCITED",
    "options": "SLIGHT_POS",
    "ordeal": "AFRAID",
    "orphan": "NEG_QUALITY",
    "ostracized": "AFRAID",
    "othered": "NEG_QUALITY",
    "otherwise": "SLIGHT_NEG",
    "ouch": "NEG_QUALITY",
    "outcast": "NEG_QUALITY",
    "outcasted": "NEG_QUALITY",
    "outed": "NEG_QUALITY",
    "outlasted": "SLIGHT_POS",
    "outpouring": "SLIGHT_POS",
    "outpourings": "SLIGHT_POS",
    "outrage": "SLIGHT_NEG",
    "outsourcing": "SLIGHT_NEG",
    "outstanding": "HAPPY",
    "overcast": "SLIGHT_NEG",
    "overcome": "EXCITED",
    "overdose": "NEG_QUALITY",
    "overdosed": "SLIGHT_NEG",
    "overdrawn": "NEG_QUALITY",
    "overlooked": "NEG_QUALITY",
    "overnight": "NEG_QUALITY",
    "overrated": "SLIGHT_NEG",
    "overreacting": "SLIGHT_NEG",
    "overstimulated": "NEG_QUALITY",
    "overtired": "SLIGHT_NEG",
    "overturned": "EXCITED",
    "overweight": "SLIGHT_NEG",
    "overwhelm": "AFRAID",
    "overwhelming": "AFRAID",
    "overworked": "NEG_QUALITY",
    "overwrought": "SLIGHT_NEG",
    "owe": "SLIGHT_NEG",
    "owes": "SLIGHT_NEG",
    "painful": "DEVASTATED",
    "painkillers": "SLIGHT_NEG",
    "palliative": "SLIGHT_NEG",
    "palpitations": "SLIGHT_NEG",
    "panicked": "SLIGHT_NEG",
    "panicking": "NEG_QUALITY",
    "paradise": "HAPPY",
    "paranoid": "SLIGHT_NEG",
    "parcel": "POS_QUALITY",
    "parched": "SLIGHT_NEG",
    "parole": "SLIGHT_POS",
    "paroled": "SLIGHT_POS",
    "participate": "HAPPY",
    "parties": "POS_QUALITY",
    "passion": "POS_QUALITY",
    "passionate": "HAPPY",
    "patch": "EXCITED",
    "patronizing": "SLIGHT_NEG",
    "pawned": "NEG_QUALITY",
    "peace": "SLIGHT_POS",
    "peaceful": "SLIGHT_POS",
    "pepper": "POS_QUALITY",
    "pepperoni": "EXCITED",
    "perfectly": "HAPPY",
    "period": "SLIGHT_NEG",
    "periods": "SLIGHT_NEG",
    "perjury": "AFRAID",
    "permanency": "SLIGHT_POS",
    "permanent": "SLIGHT_NEG",
    "permanently": "SLIGHT_NEG",
    "perseverance": "SLIGHT_POS",
    "perseverating": "SLIGHT_NEG",
    "perseveration": "SLIGHT_NEG",
    "persevered": "SLIGHT_POS",
    "persisting": "SLIGHT_POS",
    "personal": "HAPPY",
    "perspective": "POS_QUALITY",
    "pet": "POS_QUALITY",
    "petty": "DEVASTATED",
    "phenomenal": "POS_QUALITY",
    "philanthropic": "SLIGHT_POS",
    "phished": "NEG_QUALITY",
    "phishing": "SLIGHT_NEG",
    "phobia": "DEVASTATED",
    "physical": "HAPPY",
    "picky": "FRUSTRATED",
    "pictures": "SLIGHT_POS",
    "piercing": "SLIGHT_NEG",
    "pig": "POS_QUALITY",
    "pimple": "SAD",
    "pineapple": "POS_QUALITY",
    "pining": "SLIGHT_NEG",
    "pioneered": "POS_QUALITY",
    "pissoff": "NEG_QUALITY",
    "planet": "POS_QUALITY",
    "plea": "SLIGHT_NEG",
    "pleasant": "SLIGHT_POS",
    "pleasantly": "HAPPY",
    "pleasurable": "SLIGHT_POS",
    "plenty": "POS_QUALITY",
    "plodding": "SLIGHT_NEG",
    "plummeted": "AFRAID",
    "pog": "SLIGHT_POS",
    "poggers": "SLIGHT_POS",
    "poignant": "SLIGHT_POS",
    "poison": "SLIGHT_NEG",
    "poisoned": "NEG_QUALITY",
    "poisoning": "SLIGHT_NEG",
    "poisonous": "SLIGHT_NEG",
    "political": "NEG_QUALITY",
    "politics": "SAD",
    "pollution": "SLIGHT_NEG",
    "postpartum": "NEG_QUALITY",
    "potatoes": "POS_QUALITY",
    "potty": "SLIGHT_NEG",
    "pounding": "SLIGHT_NEG",
    "poverty": "SLIGHT_NEG",
    "powerless": "SAD",
    "pray": "SLIGHT_POS",
    "prayer": "HAPPY",
    "praying": "SLIGHT_POS",
    "precious": "SLIGHT_POS",
    "predatory": "FRUSTRATED",
    "predictable": "SLIGHT_NEG",
    "premature": "NEG_QUALITY",
    "prepared": "POS_QUALITY",
    "president": "POS_QUALITY",
    "pressed": "SLIGHT_NEG",
    "pressured": "SLIGHT_NEG",
    "prestigious": "HAPPY",
    "pretend": "SLIGHT_NEG",
    "pretentious": "SLIGHT_NEG",
    "previous": "SLIGHT_POS",
    "priceless": "EXCITED",
    "pricey": "NEG_QUALITY",
    "prick": "SLIGHT_NEG",
    "pride": "EXCITED",
    "probation": "SLIGHT_NEG",
    "problem": "SLIGHT_NEG",
    "professional": "POS_QUALITY",
    "prognosis": "SLIGHT_NEG",
    "progressive": "SLIGHT_NEG",
    "project": "SLIGHT_POS",
    "promising": "SLIGHT_POS",
    "property": "HAPPY",
    "proposed": "SLIGHT_POS",
    "prosecuted": "AFRAID",
    "protein": "HAPPY",
    "provider": "HAPPY",
    "ptsd": "AFRAID",
    "puke": "DEVASTATED",
    "punch": "NEG_QUALITY",
    "punched": "AFRAID",
    "punished": "SLIGHT_NEG",
    "punishes": "SLIGHT_NEG",
    "punishing": "SLIGHT_NEG",
    "puppy": "SLIGHT_POS",
    "pure": "HAPPY",
    "purge": "AFRAID",
    "purging": "AFRAID",
    "purposeless": "NEG_QUALITY",
    "pushover": "SLIGHT_NEG",
    "qualified": "HAPPY",
    "queasy": "SLIGHT_NEG",
    "quick": "POS_QUALITY",
    "quirky": "SLIGHT_NEG",
    "quit": "SLIGHT_NEG",
    "quitting": "AFRAID",
    "racing": "SLIGHT_NEG",
    "radiating": "SLIGHT_NEG",
    "rage": "SLIGHT_NEG",
    "rallying": "SLIGHT_POS",
    "raping": "NEG_QUALITY",
    "rapist": "NEG_QUALITY",
    "rash": "FRUSTRATED",
    "ratioed": "SLIGHT_NEG",
    "ratted": "AFRAID",
    "readjustment": "SLIGHT_NEG",
    "realistic": "POS_QUALITY",
    "rebuild": "SLIGHT_POS",
    "rebuilding": "SLIGHT_POS",
    "recidivism": "NEG_QUALITY",
    "recluse": "SLIGHT_NEG",
    "reclusive": "NEG_QUALITY",
    "recognize": "HAPPY",
    "recoiling": "SLIGHT_NEG",
    "recorded": "SLIGHT_NEG",
    "redundancy": "NEG_QUALITY",
    "redundant": "NEG_QUALITY",
    "reflect": "POS_QUALITY",
    "refugee": "SLIGHT_NEG",
    "refuse": "DEVASTATED",
    "regret": "SLIGHT_NEG",
    "rehomed": "SLIGHT_NEG",
    "reintegrated": "SLIGHT_POS",
    "rejection": "DEVASTATED",
    "rekt": "AFRAID",
    "relax": "HAPPY",
    "relaxed": "POS_QUALITY",
    "reliable": "POS_QUALITY",
    "relief": "SLIGHT_POS",
    "religious": "HAPPY",
    "relinquished": "NEG_QUALITY",
    "relinquishment": "NEG_QUALITY",
    "relive": "HAPPY",
    "reluctant": "NEG_QUALITY",
    "remarkable": "POS_QUALITY",
    "reminded": "SLIGHT_NEG",
    "reminds": "SLIGHT_NEG",
    "remove": "NEG_QUALITY",
    "reorg": "SLIGHT_NEG",
    "reorganization": "SLIGHT_NEG",
    "reorganized": "SLIGHT_NEG",
    "repetitive": "SLIGHT_NEG",
    "replaceable": "SLIGHT_NEG",
    "replaced": "NEG_QUALITY",
    "replacement": "SLIGHT_NEG",
    "replaying": "SLIGHT_NEG",
    "repossessed": "AFRAID",
    "repugnant": "FRUSTRATED",
    "requiem": "SLIGHT_NEG",
    "rescued": "HAPPY",
    "research": "SLIGHT_POS",
    "resentful": "NEG_QUALITY",
    "resentment": "NEG_QUALITY",
    "resilience": "POS_QUALITY",
    "resolved": "HAPPY",
    "respect": "HAPPY",
    "resplendent": "POS_QUALITY",
    "response": "POS_QUALITY",
    "responsibility": "HAPPY",
    "rest": "SLIGHT_POS",
    "restitution": "SLIGHT_POS",
    "restraining": "SLIGHT_NEG",
    "restrict": "NEG_QUALITY",
    "restricted": "SLIGHT_NEG",
    "restricting": "NEG_QUALITY",
    "restroom": "SLIGHT_POS",
    "restructured": "SLIGHT_NEG",
    "restructuring": "SLIGHT_NEG",
    "result": "SLIGHT_POS",
    "retaliation": "FRUSTRATED",
    "retire": "HAPPY",
    "retired": "SAD",
    "retraumatize": "AFRAID",
    "retraumatized": "AFRAID",
    "reunification": "SLIGHT_POS",
    "reunited": "POS_QUALITY",
    "revolting": "ANGRY",
    "rewarding": "POS_QUALITY",
    "ridiculed": "NEG_QUALITY",
    "ridiculous": "SLIGHT_NEG",
    "rip": "SLIGHT_NEG",
    "ripped": "FRUSTRATED",
    "rippedoff": "NEG_QUALITY",
    "ritualistic": "SLIGHT_NEG",
    "rizz": "SLIGHT_POS",
    "roach": "SLIGHT_NEG",
    "robbed": "SLIGHT_NEG",
    "robber": "SLIGHT_NEG",
    "roll": "SLIGHT_POS",
    "roller": "EXCITED",
    "romantic": "HAPPY",
    "rope": "SLIGHT_NEG",
    "rotting": "SLIGHT_NEG",
    "rough": "SLIGHT_NEG",
    "rubbish": "NEG_QUALITY",
    "rubble": "AFRAID",
    "rude": "FRUSTRATED",
    "ruin": "SLIGHT_NEG",
    "ruined": "SLIGHT_NEG",
    "ruining": "SLIGHT_NEG",
    "ruledout": "SLIGHT_NEG",
    "ruminate": "NEG_QUALITY",
    "rumination": "NEG_QUALITY",
    "rumor": "SLIGHT_NEG",
    "rumors": "SLIGHT_NEG",
    "sabotage": "SLIGHT_NEG",
    "sabotaged": "SLIGHT_NEG",
    "sabotaging": "SLIGHT_NEG",
    "sacrificing": "SLIGHT_NEG",
    "sadness": "SLIGHT_NEG",
    "safe": "SLIGHT_POS",
    "safely": "HAPPY",
    "safety": "POS_QUALITY",
    "sagging": "SLIGHT_NEG",
    "sales": "SLIGHT_POS",
    "salty": "SLIGHT_NEG",
    "sanctuary": "SLIGHT_POS",
    "sank": "SLIGHT_NEG",
    "santa": "HAPPY",
    "saved": "HAPPY",
    "saving": "POS_QUALITY",
    "scale": "NEG_QUALITY",
    "scam": "DEVASTATED",
    "scammed": "AFRAID",
    "scandal": "NEG_QUALITY",
    "scapegoat": "AFRAID",
    "scapegoated": "NEG_QUALITY",
    "scares": "SLIGHT_NEG",
    "scariest": "SLIGHT_NEG",
    "scarring": "SLIGHT_NEG",
    "scary": "AFRAID",
    "scold": "ANGRY",
    "scorching": "SLIGHT_NEG",
    "scream": "SLIGHT_NEG",
    "screamed": "SLIGHT_NEG",
    "screenshot": "SLIGHT_NEG",
    "screenshots": "SLIGHT_NEG",
    "screenshotted": "SLIGHT_NEG",
    "screwed": "SLIGHT_NEG",
    "scummy": "NEG_QUALITY",
    "secluded": "SLIGHT_NEG",
    "seclusion": "SLIGHT_NEG",
    "secret": "SLIGHT_NEG",
    "secure": "POS_QUALITY",
    "seize": "POS_QUALITY",
    "self-doubt": "SLIGHT_NEG",
    "self-hatred": "AFRAID",
    "self-loathing": "AFRAID",
    "self-sabotage": "NEG_QUALITY",
    "selfless": "POS_QUALITY",
    "sellout": "AFRAID",
    "semi": "NEG_QUALITY",
    "sentencing": "AFRAID",
    "separation": "NEG_QUALITY",
    "serenity": "POS_QUALITY",
    "severe": "SLIGHT_NEG",
    "shackled": "DEVASTATED",
    "shade": "SLIGHT_NEG",
    "shadowbanned": "SLIGHT_NEG",
    "shaking": "SLIGHT_NEG",
    "shallow": "SLIGHT_NEG",
    "shame": "DEVASTATED",
    "sheesh": "NEG_QUALITY",
    "shipping": "EXCITED",
    "shit": "SLIGHT_NEG",
    "shivering": "SLIGHT_NEG",
    "shock": "NEG_QUALITY",
    "shooting": "FRUSTRATED",
    "shot": "SLIGHT_NEG",
    "shoved": "NEG_QUALITY",
    "shredded": "NEG_QUALITY",
    "shrieking": "FRUSTRATED",
    "shrill": "SLIGHT_NEG",
    "shrink": "SLIGHT_NEG",
    "shrinking": "SLIGHT_NEG",
    "shunned": "AFRAID",
    "shutdown": "SLIGHT_NEG",
    "shutoff": "NEG_QUALITY",
    "shutup": "NEG_QUALITY",
    "sickening": "ANGRY",
    "sickness": "SLIGHT_NEG",
    "sided": "SLIGHT_NEG",
    "sidelined": "SLIGHT_NEG",
    "sighing": "SLIGHT_NEG",
    "silenced": "SAD",
    "silencing": "NEG_QUALITY",
    "silent": "SLIGHT_NEG",
    "silly": "SLIGHT_NEG",
    "simp": "SLIGHT_NEG",
    "sincere": "SLIGHT_POS",
    "sing": "EXCITED",
    "singled": "SLIGHT_NEG",
    "sinking": "SAD",
    "sis": "POS_QUALITY",
    "site": "POS_QUALITY",
    "situationship": "SLIGHT_NEG",
    "skank": "FRUSTRATED",
    "skating": "EXCITED",
    "sketchy": "NEG_QUALITY",
    "skunk": "SAD",
    "slapped": "AFRAID",
    "slapping": "FRUSTRATED",
    "slaps": "EXCITED",
    "slay": "SLIGHT_POS",
    "slayed": "SLIGHT_POS",
    "slaying": "SLIGHT_POS",
    "sleazy": "NEG_QUALITY",
    "sleep": "SLIGHT_POS",
    "sleep-deprived": "NEG_QUALITY",
    "sleepless": "SLIGHT_NEG",
    "sleepy": "HAPPY",
    "slimy": "NEG_QUALITY",
    "slipped": "NEG_QUALITY",
    "slit": "SLIGHT_NEG",
    "slut": "SLIGHT_NEG",
    "smack": "NEG_QUALITY",
    "smaller": "NEG_QUALITY",
    "smart": "HAPPY",
    "smash": "NEG_QUALITY",
    "smashed": "NEG_QUALITY",
    "smh": "SLIGHT_NEG",
    "smoke": "SLIGHT_NEG",
    "smoking": "NEG_QUALITY",
    "snakes": "ANGRY",
    "snatched": "POS_QUALITY",
    "sneaky": "NEG_QUALITY",
    "sniper": "SLIGHT_NEG",
    "snitch": "SLIGHT_NEG",
    "snitched": "SLIGHT_NEG",
    "snubbed": "SLIGHT_NEG",
    "snuck": "NEG_QUALITY",
    "soaring": "EXCITED",
    "sobbing": "AFRAID",
    "sobriety": "SLIGHT_POS",
    "social": "SLIGHT_POS",
    "society": "POS_QUALITY",
    "soldout": "SLIGHT_NEG",
    "solution": "POS_QUALITY",
    "solve": "POS_QUALITY",
    "somewhere": "SLIGHT_NEG",
    "sore": "SLIGHT_NEG",
    "sorrow": "SAD",
    "soulless": "NEG_QUALITY",
    "source": "HAPPY",
    "spammed": "SLIGHT_NEG",
    "speed": "POS_QUALITY",
    "spiders": "AFRAID",
    "spilled": "SLIGHT_NEG",
    "spineless": "NEG_QUALITY",
    "spiral": "SLIGHT_NEG",
    "spirit": "EXCITED",
    "spit": "SLIGHT_NEG",
    "splendid": "SLIGHT_POS",
    "split": "NEG_QUALITY",
    "spoiled": "FRUSTRATED",
    "spoonie": "SLIGHT_NEG",
    "spoons": "SLIGHT_NEG",
    "spouse": "SLIGHT_POS",
    "spread": "SLIGHT_NEG",
    "squid": "POS_QUALITY",
    "stab": "AFRAID",
    "stabbing": "AFRAID",
    "staff": "HAPPY",
    "stale": "SLIGHT_NEG",
    "stalk": "FRUSTRATED",
    "stalked": "AFRAID",
    "stalker": "FRUSTRATED",
    "stalking": "FRUSTRATED",
    "stan": "EXCITED",
    "startled": "NEG_QUALITY",
    "starvation": "DEVASTATED",
    "starved": "SLIGHT_NEG",
    "starving": "AFRAID",
    "stateless": "AFRAID",
    "steadfast": "SLIGHT_POS",
    "steal": "ANGRY",
    "stealing": "NEG_QUALITY",
    "stfu": "SLIGHT_NEG",
    "stick": "SLIGHT_POS",
    "stiffness": "SLIGHT_NEG",
    "stigma": "NEG_QUALITY",
    "stigmatized": "NEG_QUALITY",
    "stillbirth": "SLIGHT_NEG",
    "stillborn": "SLIGHT_NEG",
    "stimming": "SLIGHT_POS",
    "stinging": "SLIGHT_NEG",
    "stole": "FRUSTRATED",
    "stolen": "FRUSTRATED",
    "stonewalling": "NEG_QUALITY",
    "storm": "AFRAID",
    "stormed": "SLIGHT_NEG",
    "storming": "FRUSTRATED",
    "stormy": "SLIGHT_NEG",
    "stranded": "SLIGHT_NEG",
    "strangled": "DEVASTATED",
    "stress": "SLIGHT_NEG",
    "stressed": "AFRAID",
    "stressedout": "SLIGHT_NEG",
    "stressful": "SLIGHT_NEG",
    "stroke": "SLIGHT_NEG",
    "struggle": "SLIGHT_NEG",
    "struggled": "DEVASTATED",
    "struggling": "NEG_QUALITY",
    "stubbed": "NEG_QUALITY",
    "student": "EXCITED",
    "stumbled": "DEVASTATED",
    "sublime": "POS_QUALITY",
    "submerged": "AFRAID",
    "subpoena": "SLIGHT_NEG",
    "subpoenaed": "SLIGHT_NEG",
    "subtweeted": "SLIGHT_NEG",
    "succeed": "POS_QUALITY",
    "successfully": "HAPPY",
    "suck": "NEG_QUALITY",
    "sucks": "FRUSTRATED",
    "sue": "FRUSTRATED",
    "suffer": "SLIGHT_NEG",
    "suffering": "SLIGHT_NEG",
    "summa": "POS_QUALITY",
    "sundowning": "AFRAID",
    "sunny": "HAPPY",
    "superb": "POS_QUALITY",
    "surrender": "SLIGHT_NEG",
    "survival": "SLIGHT_POS",
    "survive": "SLIGHT_POS",
    "survived": "SLIGHT_POS",
    "survivors": "SLIGHT_NEG",
    "swallow": "EXCITED",
    "swatted": "AFRAID",
    "swear": "SLIGHT_NEG",
    "sweat": "AFRAID",
    "sweating": "AFRAID",
    "sweaty": "SAD",
    "sweet": "SLIGHT_POS",
    "swift": "EXCITED",
    "swindled": "AFRAID",
    "switch": "POS_QUALITY",
    "sympathy": "HAPPY",
    "symphony": "SLIGHT_POS",
    "talent": "POS_QUALITY",
    "tanked": "AFRAID",
    "tantrum": "NEG_QUALITY",
    "tantrums": "NEG_QUALITY",
    "tattled": "SLIGHT_NEG",
    "taunted": "NEG_QUALITY",
    "taxes": "SLIGHT_NEG",
    "tear": "AFRAID",
    "tears": "SLIGHT_NEG",
    "teased": "SLIGHT_NEG",
    "tech": "POS_QUALITY",
    "tedious": "SLIGHT_NEG",
    "teething": "SLIGHT_NEG",
    "tempestuous": "SLIGHT_NEG",
    "temptation": "SLIGHT_NEG",
    "tenacious": "SLIGHT_POS",
    "tenacity": "SLIGHT_POS",
    "tensing": "SLIGHT_NEG",
    "tent": "EXCITED",
    "tenured": "SLIGHT_POS",
    "termination": "NEG_QUALITY",
    "terrific": "SLIGHT_POS",
    "terrifying": "SLIGHT_NEG",
    "terror": "NEG_QUALITY",
    "terrorism": "SLIGHT_NEG",
    "terrorist": "FRUSTRATED",
    "terrorists": "FRUSTRATED",
    "testified": "SLIGHT_NEG",
    "thankfully": "HAPPY",
    "thankless": "NEG_QUALITY",
    "thick": "HAPPY",
    "thieves": "SLIGHT_NEG",
    "thoughtful": "HAPPY",
    "threat": "NEG_QUALITY",
    "threatened": "SLIGHT_NEG",
    "threatening": "NEG_QUALITY",
    "threatens": "SLIGHT_NEG",
    "thrift": "HAPPY",
    "thriving": "EXCITED",
    "throbbing": "SLIGHT_NEG",
    "thrownout": "NEG_QUALITY",
    "tight": "FRUSTRATED",
    "tightness": "SLIGHT_NEG",
    "tilted": "SLIGHT_NEG",
    "tiresome": "SLIGHT_NEG",
    "toe": "SLIGHT_POS",
    "top": "EXCITED",
    "torn": "AFRAID",
    "tornado": "DEVASTATED",
    "total": "HAPPY",
    "touching": "SLIGHT_POS",
    "towed": "SLIGHT_NEG",
    "toxic": "FRUSTRATED",
    "trafficked": "DEVASTATED",
    "trafficking": "SLIGHT_NEG",
    "tragedy": "SLIGHT_NEG",
    "tragic": "SLIGHT_NEG",
    "trainer": "POS_QUALITY",
    "traitorous": "DEVASTATED",
    "transcendent": "POS_QUALITY",
    "transitioned": "SLIGHT_POS",
    "transphobia": "FRUSTRATED",
    "transphobic": "FRUSTRATED",
    "trap": "AFRAID",
    "traps": "FRUSTRATED",
    "trash": "NEG_QUALITY",
    "trauma": "SLIGHT_NEG",
    "traumatic": "SLIGHT_NEG",
    "traumatized": "NEG_QUALITY",
    "traumatizing": "NEG_QUALITY",
    "treachery": "DEVASTATED",
    "treat": "HAPPY",
    "tremble": "SLIGHT_NEG",
    "trembles": "SLIGHT_NEG",
    "trembling": "SLIGHT_NEG",
    "triage": "SLIGHT_NEG",
    "triangulating": "NEG_QUALITY",
    "tricky": "FRUSTRATED",
    "triggered": "AFRAID",
    "tripped": "DEVASTATED",
    "triumph": "EXCITED",
    "triumphant": "EXCITED",
    "trolled": "SLIGHT_NEG",
    "trouble": "SLIGHT_NEG",
    "trump": "SLIGHT_POS",
    "trust": "SLIGHT_POS",
    "trusted": "SLIGHT_NEG",
    "trustworthy": "POS_QUALITY",
    "tsunami": "DEVASTATED",
    "turbulent": "SLIGHT_NEG",
    "turncoat": "AFRAID",
    "turtle": "NEG_QUALITY",
    "twins": "HAPPY",
    "twisted": "SLIGHT_NEG",
    "twists": "SLIGHT_NEG",
    "two-faced": "AFRAID",
    "unacceptable": "ANGRY",
    "unadoptable": "SLIGHT_NEG",
    "unalive": "SAD",
    "unanswered": "SLIGHT_NEG",
    "unappreciated": "NEG_QUALITY",
    "unapproachable": "SLIGHT_NEG",
    "unaware": "DEVASTATED",
    "unbearable": "ANGRY",
    "unbreakable": "SLIGHT_POS",
    "unchosen": "NEG_QUALITY",
    "uncomfortable": "NEG_QUALITY",
    "undaunted": "SLIGHT_POS",
    "undermining": "NEG_QUALITY",
    "underpaid": "NEG_QUALITY",
    "underwater": "SLIGHT_NEG",
    "underweight": "SLIGHT_NEG",
    "undeserving": "NEG_QUALITY",
    "undocumented": "SLIGHT_NEG",
    "uneasy": "NEG_QUALITY",
    "unemployable": "NEG_QUALITY",
    "unemployed": "NEG_QUALITY",
    "unemployment": "SLIGHT_NEG",
    "unexpectedly": "SLIGHT_NEG",
    "unfit": "SLIGHT_NEG",
    "unfollowed": "SLIGHT_NEG",
    "unfortunately": "AFRAID",
    "unfriended": "NEG_QUALITY",
    "unfunny": "SLIGHT_NEG",
    "unhoused": "AFRAID",
    "uninhabitable": "AFRAID",
    "uninspired": "SLIGHT_NEG",
    "uninvited": "SLIGHT_NEG",
    "university": "HAPPY",
    "unless": "SLIGHT_NEG",
    "unlikely": "SAD",
    "unlovable": "NEG_QUALITY",
    "unlucky": "NEG_QUALITY",
    "unmanageable": "NEG_QUALITY",
    "unmasking": "SLIGHT_POS",
    "unmatched": "SLIGHT_NEG",
    "unmoored": "SLIGHT_NEG",
    "unnecessary": "SAD",
    "unnoticed": "NEG_QUALITY",
    "unpopular": "SLIGHT_NEG",
    "unprepared": "DEVASTATED",
    "unraveling": "SLIGHT_NEG",
    "unredeemable": "SAD",
    "unresponsive": "AFRAID",
    "unsafe": "AFRAID",
    "untethered": "SLIGHT_NEG",
    "unwanted": "NEG_QUALITY",
    "unwavering": "SLIGHT_POS",
    "unwelcome": "NEG_QUALITY",
    "unworthy": "NEG_QUALITY",
    "uplifting": "SLIGHT_POS",
    "uprooted": "AFRAID",
    "upset": "AFRAID",
    "vacation": "SLIGHT_POS",
    "valid": "SLIGHT_POS",
    "validating": "POS_QUALITY",
    "valor": "EXCITED",
    "valued": "HAPPY",
    "vanish": "NEG_QUALITY",
    "vanished": "NEG_QUALITY",
    "ventilator": "AFRAID",
    "vertigo": "SLIGHT_NEG",
    "viable": "SLIGHT_POS",
    "vibe": "SLIGHT_POS",
    "vibes": "SLIGHT_POS",
    "victim": "SLIGHT_NEG",
    "victorious": "EXCITED",
    "victory": "HAPPY",
    "vile": "ANGRY",
    "villain": "SLIGHT_NEG",
    "vindicated": "HAPPY",
    "vindication": "HAPPY",
    "violated": "NEG_QUALITY",
    "violation": "NEG_QUALITY",
    "violence": "SLIGHT_NEG",
    "violent": "SLIGHT_NEG",
    "virtuoso": "POS_QUALITY",
    "visitation": "SLIGHT_NEG",
    "vomiting": "SLIGHT_NEG",
    "vulnerable": "SLIGHT_NEG",
    "wailing": "AFRAID",
    "waitlisted": "SLIGHT_NEG",
    "wallflower": "SLIGHT_NEG",
    "walls": "SLIGHT_NEG",
    "wandering": "NEG_QUALITY",
    "waning": "SLIGHT_NEG",
    "warm": "POS_QUALITY",
    "warn": "SLIGHT_NEG",
    "warned": "NEG_QUALITY",
    "warning": "SLIGHT_NEG",
    "warrant": "NEG_QUALITY",
    "washedout": "SLIGHT_NEG",
    "wasn't": "SLIGHT_NEG",
    "waste": "NEG_QUALITY",
    "wasted": "SLIGHT_NEG",
    "watermelon": "POS_QUALITY",
    "wealthy": "HAPPY",
    "weapon": "SLIGHT_NEG",
    "weaponize": "NEG_QUALITY",
    "weaponized": "NEG_QUALITY",
    "weapons": "SLIGHT_NEG",
    "wedgie": "SLIGHT_NEG",
    "weird": "SLIGHT_NEG",
    "weirdo": "SLIGHT_NEG",
    "welcome": "HAPPY",
    "welfare": "SLIGHT_NEG",
    "werent": "SAD",
    "whatever": "SLIGHT_NEG",
    "wheelchair": "SLIGHT_NEG",
    "whining": "SLIGHT_NEG",
    "whoa": "SLIGHT_NEG",
    "whore": "SLIGHT_NEG",
    "widow": "NEG_QUALITY",
    "wifidown": "SLIGHT_NEG",
    "wild": "SLIGHT_NEG",
    "wildfire": "FRUSTRATED",
    "wilting": "SLIGHT_NEG",
    "wimp": "SLIGHT_NEG",
    "win": "SLIGHT_POS",
    "wincing": "SLIGHT_NEG",
    "winner": "POS_QUALITY",
    "winnings": "POS_QUALITY",
    "wins": "HAPPY",
    "wipedout": "SLIGHT_NEG",
    "wisdom": "HAPPY",
    "wise": "POS_QUALITY",
    "wisely": "HAPPY",
    "withdrawal": "AFRAID",
    "withdrawing": "SLIGHT_NEG",
    "withdrawn": "NEG_QUALITY",
    "withering": "SLIGHT_NEG",
    "withstood": "SLIGHT_POS",
    "wolf": "POS_QUALITY",
    "wonders": "HAPPY",
    "wooden": "SLIGHT_NEG",
    "worker": "POS_QUALITY",
    "worry": "NEG_QUALITY",
    "worse": "AFRAID",
    "worst": "NEG_QUALITY",
    "worthless": "NEG_QUALITY",
    "worthy": "SLIGHT_POS",
    "wound": "AFRAID",
    "wow": "SLIGHT_POS",
    "wracking": "FRUSTRATED",
    "wreck": "DEVASTATED",
    "wreckage": "AFRAID",
    "wrecked": "NEG_QUALITY",
    "wretched": "NEG_QUALITY",
    "wrongful": "AFRAID",
    "wrongfully": "AFRAID",
    "xbox": "POS_QUALITY",
    "xenophobia": "FRUSTRATED",
    "yay": "SLIGHT_POS",
    "yearning": "NEG_QUALITY",
    "yeet": "SLIGHT_POS",
    "yell": "FRUSTRATED",
    "yelled": "SLIGHT_NEG",
    "yelling": "FRUSTRATED",
    "yikes": "SLIGHT_NEG",
    "yoga": "HAPPY",
    "yolo": "SLIGHT_POS",
    "youngest": "POS_QUALITY",
    "yuck": "SAD",
    "zombie": "AFRAID",
    "zoo": "HAPPY",


    # ── Domain overrides (AFTER auto-import — last-write-wins) ───────────
    # These override coarse auto-mappings with domain-specific roots.
    # Must be LAST in the dict to take priority over auto-import.

    # Financial
    "funded": "FIN_POS", "funding": "FIN_POS", "approved": "FIN_POS",
    "profit": "FIN_POS", "bonus": "FIN_POS", "savings": "FIN_POS",
    "invested": "FIN_POS", "raise": "FIN_POS",
    "debt": "FIN_NEG", "bankrupt": "FIN_NEG", "bankruptcy": "FIN_NEG",
    "overdue": "FIN_NEG", "foreclosure": "FIN_NEG", "evicted": "FIN_NEG",
    "overdraft": "FIN_NEG", "broke": "FIN_NEG", "bills": "FIN_NEG",

    # Medical
    "healed": "MED_POS", "remission": "MED_POS", "recovered": "MED_POS",
    "recovery": "MED_POS", "cured": "MED_POS", "cleared": "MED_POS",
    "diagnosed": "MED_NEG", "diagnosis": "MED_NEG", "terminal": "MED_NEG",
    "relapsed": "MED_NEG", "relapse": "MED_NEG", "tumor": "MED_NEG",
    "cancer": "MED_NEG", "chemo": "MED_NEG", "chemotherapy": "MED_NEG",

    # Academic
    "graduated": "ACAD_POS", "honors": "ACAD_POS", "scholarship": "ACAD_POS",
    "failed": "ACAD_NEG", "expelled": "ACAD_NEG", "flunked": "ACAD_NEG",
    "suspended": "ACAD_NEG",

    # Legal
    "acquitted": "LEGAL_POS", "pardoned": "LEGAL_POS", "innocent": "LEGAL_POS",
    "exonerated": "LEGAL_POS",
    "arrested": "LEGAL_NEG", "convicted": "LEGAL_NEG", "sentenced": "LEGAL_NEG",
    "sued": "LEGAL_NEG", "indicted": "LEGAL_NEG", "prison": "LEGAL_NEG",
    "jail": "LEGAL_NEG",

    # Career
    "promoted": "CAREER_POS", "promotion": "CAREER_POS", "hired": "CAREER_POS",
    "recognized": "CAREER_POS", "awarded": "CAREER_POS", "earned": "CAREER_POS",
    "fired": "CAREER_NEG", "demoted": "CAREER_NEG", "terminated": "CAREER_NEG",
    "downsized": "CAREER_NEG",

    # Relationship
    "engaged": "REL_POS", "married": "REL_POS", "dating": "REL_POS",
    "reconnected": "REL_POS",
    "divorced": "REL_NEG", "dumped": "REL_NEG", "ghosted": "REL_NEG",
    "rejected": "REL_NEG", "cheated": "REL_NEG", "separated": "REL_NEG",

    # ── Promoted from SLIGHT_NEG — too weak for negative sentences ───────
    "grave":       "NEG_QUALITY",
    "disease":     "MED_NEG",
    "sick":        "MED_NEG",
    "illness":     "MED_NEG",
    "divorce":     "REL_NEG",
    "stupid":      "SOC_EVAL_NEG",
    "lying":       "SOC_EVAL_NEG",
    "screaming":   "NEG_QUALITY",
    "screams":     "NEG_QUALITY",
    "battle":      "NEG_QUALITY",
    "fight":       "NEG_QUALITY",
    "fighting":    "NEG_QUALITY",
    "solitude":    "LONELY",
    "pretended":   "NEG_QUALITY",
    "pretending":  "NEG_QUALITY",
    "threw":       "FILLER_WORD",
    "muffled":     "FILLER_WORD",
    "judgment":    "NEG_QUALITY",
    "tempted":     "NEG_QUALITY",
    "spent":       "FILLER_WORD",
    "end":         "FILLER_WORD",

    # ── Narrative/descriptive words that shouldn't carry emotional charge ──
    "staff":       "FILLER_WORD",     # noun, not emotional
    "personal":    "FILLER_WORD",     # adjective, descriptive
    "quick":       "FILLER_WORD",     # speed descriptor
    "quickly":     "FILLER_WORD",
    "number":      "FILLER_WORD",     # math/count, not emotional
    "become":      "FILLER_WORD",     # verb of state change, neutral
    "becoming":    "FILLER_WORD",
    "became":      "FILLER_WORD",
    "wandering":   "FILLER_WORD",     # motion descriptor
    "wander":      "FILLER_WORD",
    "spirit":      "FILLER_WORD",     # context-dependent — "team spirit" vs "spiritual"
    "recognized":  "FILLER_WORD",     # override CAREER_POS — neutral in narrative
    "fine":        "FILLER_WORD",     # too ambiguous ("I'm fine" = masking OR genuine)
    "hope":        "SLIGHT_POS",      # override POS_QUALITY — mild, not definitive
    "hoping":      "SLIGHT_POS",
    "pay":         "FILLER_WORD",     # override FIN_NEG — "pay" alone is neutral
    "mean":        "FILLER_WORD",     # override SOC_EVAL_NEG — "what does it mean" is neutral
    "wound":       "FILLER_WORD",     # override AFRAID — "wound" in narrative is descriptive
    "drowning":    "FILLER_WORD",     # override AFRAID — often metaphorical in narrative
    "prison":      "FILLER_WORD",     # setting, not emotion — "he went to prison" is descriptive

    # ── Achievement / success words (novel-500 gap analysis) ─────────────
    "figured":     "ACHIEVEMENT",     # "figured out the bug"
    "managed":     "SLIGHT_POS",      # "managed to do X"
    "finally":     "SLIGHT_POS",      # "finally X" = relief/achievement
    "blessed":     "GRATEFUL",        # "so blessed"
    "rested":      "CONTENT",         # "feel rested"
    "slayed":      "POS_QUALITY",     # slang positive
    "slay":        "POS_QUALITY",
    "incredible":  "HAPPY",           # strong positive eval
    "insanely":    "INTENSIFY",       # override — intensifier not neg
    "perfectly":   "POS_QUALITY",
    "maple":       "FILLER_WORD",     # food item, not emotional
    "pancakes":    "FILLER_WORD",
    "syrup":       "FILLER_WORD",
    "breeze":      "FILLER_WORD",     # weather descriptor
    "alarm":       "FILLER_WORD",
    "cloud":       "FILLER_WORD",
    "race":        "FILLER_WORD",
    "crumbs":      "FILLER_WORD",     # slang: "left no crumbs" = did well

    # ── Negative event/situation words (novel-500 gap) ───────────────────
    "cancelled":   "NEG_QUALITY",
    "canceled":    "NEG_QUALITY",
    "sideswiped":  "NEG_QUALITY",
    "leaking":     "NEG_QUALITY",
    "scratched":   "SLIGHT_NEG",
    "dropped":     "SLIGHT_NEG",
    "audited":     "NEG_QUALITY",
    "blocked":     "NEG_QUALITY",
    "soaked":      "SLIGHT_NEG",
    "bleeding":    "NEG_QUALITY",
    "failing":     "ACAD_NEG",
    "poison":      "MED_NEG",
    "closed":      "SLIGHT_NEG",
    "backed":      "SLIGHT_NEG",

    # ── Direction words — need DIRECTIONAL bond sites ────────────────────
    # These are FILLER for charge but carry structural bonding potential.
    # Re-mapped to MOTION so they get DIRECTIONAL bond sites from CATEGORY_BONDS.
    # Financial context words — need charge for sarcasm detection
    "paying":      "FIN_NEG",         # spending money = financial negative context
    "pay":         "FIN_NEG",
    "cost":        "FIN_NEG",
    "costs":       "FIN_NEG",
    "spend":       "FIN_NEG",
    "spending":    "FIN_NEG",
    "expensive":   "FIN_NEG",
    "price":       "FIN_NEG",
    "fee":         "FIN_NEG",
    "charge":      "FIN_NEG",
    "dollars":     "FILLER_WORD",     # override V8 dV=+35 (neutral unit of currency)
    "dollar":      "FILLER_WORD",
    "money":       "FILLER_WORD",

    # Negative context words for sarcasm detection
    "delayed":     "SLIGHT_NEG",
    "delay":       "SLIGHT_NEG",
    "traffic":     "SLIGHT_NEG",
    "parking":     "SLIGHT_NEG",
    "waiting":     "SLIGHT_NEG",
    "wait":        "SLIGHT_NEG",
    "forgot":      "NEG_QUALITY",
    "forgotten":   "NEG_QUALITY",
    "forget":      "FILLER_WORD",     # imperative "forget it" is different
    "broke":       "FIN_NEG",
    "broken":      "NEG_QUALITY",
    "tiny":        "FILLER_WORD",     # override V8 — "tiny" is descriptive, not emotional
    "small":       "FILLER_WORD",
    "empty":       "NEG_QUALITY",

    "off":         "MOTION",
    "away":        "MOTION",
    "out":         "MOTION",
    "back":        "MOTION",
    "down":        "MOTION",          # override the earlier FILLER_WORD
    "up":          "MOTION",
    "over":        "MOTION",
    "through":     "MOTION",
}

# ---------------------------------------------------------------------------
# Suffix stripping — try longer suffixes first; min stem length enforced
# ---------------------------------------------------------------------------

# Each entry: (suffix, min_stem_length)
_SUFFIXES: list[tuple[str, int]] = [
    # 7-char suffixes
    ("fulness",  7),
    ("lessly",   6),
    ("ingness",  7),
    # 6-char suffixes
    # (none beyond above at 6)
    # 4-5 char suffixes
    ("ness",     4),
    ("ment",     4),
    ("tion",     4),
    ("sion",     4),
    ("less",     4),
    ("able",     4),
    ("ible",     4),
    # 3-char suffixes
    ("ful",      3),
    ("ous",      3),
    ("ive",      3),
    ("ity",      3),
    ("ing",      3),
    ("est",      3),
    ("ling",     3),
    # 2-char suffixes
    ("ly",       2),
    ("ed",       2),
    ("er",       2),
    ("es",       2),
    # 1-char suffixes
    ("s",        1),
]


def _strip_suffix(word: str) -> str | None:
    """
    Try removing known suffixes from longest to shortest.
    Returns the stem if a suffix was removed and the stem meets minimum
    length; returns None if no suffix matched.
    """
    for suffix, min_stem in _SUFFIXES:
        if word.endswith(suffix) and len(word) - len(suffix) >= min_stem:
            return word[: -len(suffix)]
    return None


# Punctuation characters to strip from token edges
_PUNCT = string.punctuation + "\u2026\u2013\u2014"  # … – —
_PUNCT_TABLE = str.maketrans("", "", _PUNCT)


def _candidate_stems(word: str) -> list[str]:
    """
    Return candidate stems to try after suffix stripping.
    Handles English i→y spelling restoration (happiness → happi → happy).
    """
    stem = _strip_suffix(word)
    if stem is None:
        return []
    candidates = [stem]
    # i → y restoration: "happi" → "happy", "anxi" → "anxy" (won't match, harmless)
    if stem.endswith("i"):
        candidates.append(stem[:-1] + "y")
    # doubled consonant removal: "running" → "runn" → "run"
    if len(stem) >= 2 and stem[-1] == stem[-2]:
        candidates.append(stem[:-1])
    return candidates


def map_to_root(word: str) -> Root:
    """
    Map a single English word to its V9 Root via three-tier lookup.

    Tier 1 — Direct: lowercase + strip punctuation, look up in WORD_TO_ROOT.
    Tier 2 — Morphological: strip one suffix, look up stem in WORD_TO_ROOT.
    Tier 3 — Fallback: return ROOTS["OBJECT_GENERIC"] (GAS, zero charge).
    """
    # Clean: lowercase, remove punctuation
    clean = word.lower().translate(_PUNCT_TABLE).strip()

    # Tier 1: direct lookup
    if clean in WORD_TO_ROOT:
        return ROOTS[WORD_TO_ROOT[clean]]

    # Tier 2: morphological stripping (with spelling normalization)
    for stem in _candidate_stems(clean):
        if stem in WORD_TO_ROOT:
            return ROOTS[WORD_TO_ROOT[stem]]

    # Tier 3: generic fallback
    return ROOTS["OBJECT_GENERIC"]
